// Domain vocabulary: the Corporate Finance and mathematical/quantitative English that the general
// verb/adjective bank doesn't cover. Deliberately noun- and term-heavy, because that is what this
// register actually consists of.
//
// Entry shape: [en, de (pipe-separated), enSentence, deSentence, collocations (pipe-separated),
// type, definition?]
//
// `definition` is the English gloss used as the exercise prompt for jargon that has no clean German
// equivalent — EBITDA, covenant, carry. Leave it off whenever the German translation is the honest
// anchor for the term (liability → Verbindlichkeit), and the word is then drilled the same way the
// general vocabulary is. See buildDomainWords() in vocab.ts.
export type DomainEntry = [
  en: string,
  de: string,
  enSentence: string,
  deSentence: string,
  collocations: string,
  type: "noun" | "verb" | "adjective" | "term",
  definition?: string,
];

// ---------------------------------------------------------------------------
// Corporate Finance — financial statements and accounting
// ---------------------------------------------------------------------------

export const FIN_ACCOUNTING: DomainEntry[] = [
["balance sheet","Bilanz","The balance sheet shows what the company owns and owes at year end.","Die Bilanz zeigt, was das Unternehmen zum Jahresende besitzt und schuldet.","on the balance sheet|balance sheet item","term"],
["income statement","Gewinn- und Verlustrechnung","The income statement runs from revenue down to net income.","Die Gewinn- und Verlustrechnung läuft vom Umsatz bis zum Jahresüberschuss.","consolidated income statement|income statement line","term"],
["cash flow statement","Kapitalflussrechnung","The cash flow statement reconciles net income to actual cash.","Die Kapitalflussrechnung überleitet den Jahresüberschuss auf den tatsächlichen Zahlungsmittelzufluss.","statement of cash flows|operating cash flow","term"],
["revenue","Umsatz|Erlöse","Revenue grew twelve percent year on year.","Der Umsatz wuchs zwölf Prozent im Jahresvergleich.","recurring revenue|revenue growth","noun"],
["gross profit","Rohertrag|Bruttogewinn","Gross profit is revenue less the cost of goods sold.","Der Rohertrag ist der Umsatz abzüglich der Herstellungskosten.","gross profit margin|report gross profit","term"],
["operating income","Betriebsergebnis","Operating income excludes interest and taxes.","Das Betriebsergebnis schließt Zinsen und Steuern aus.","operating income margin|adjusted operating income","term"],
["net income","Jahresüberschuss|Nettogewinn","Net income is the bottom line of the income statement.","Der Jahresüberschuss ist die letzte Zeile der Gewinn- und Verlustrechnung.","report net income|net income attributable to","term"],
["cost of goods sold","Herstellungskosten des Umsatzes","Cost of goods sold rose faster than revenue last quarter.","Die Herstellungskosten des Umsatzes stiegen im letzten Quartal schneller als der Umsatz.","COGS|cost of sales","term"],
["overhead","Gemeinkosten","Management cut overhead by closing two regional offices.","Das Management senkte die Gemeinkosten durch die Schließung zweier Regionalbüros.","overhead costs|allocate overhead","noun"],
["accrual","Abgrenzung|Rückstellung","Under accrual accounting, revenue is booked when earned, not when paid.","Nach der Periodenabgrenzung wird der Umsatz erfasst, wenn er verdient ist, nicht wenn er bezahlt wird.","accrual accounting|accrual basis","noun","Recognising revenue and costs in the period they arise, not when the cash actually moves."],
["depreciation","Abschreibung","Depreciation spreads the cost of a machine over its useful life.","Die Abschreibung verteilt die Kosten einer Maschine über ihre Nutzungsdauer.","straight-line depreciation|accumulated depreciation","noun"],
["amortisation","Amortisation|Abschreibung immaterieller Vermögenswerte","Amortisation applies the same logic as depreciation, but to intangible assets.","Die Amortisation folgt derselben Logik wie die Abschreibung, betrifft aber immaterielle Vermögenswerte.","amortisation schedule|amortisation of intangibles","noun","The gradual write-down of an intangible asset, or of a loan principal, over time."],
["impairment","Wertminderung","The group booked a large impairment on the acquired brand.","Der Konzern verbuchte eine hohe Wertminderung auf die erworbene Marke.","impairment charge|test for impairment","noun"],
["goodwill","Firmenwert","Goodwill is what the buyer paid above the fair value of the net assets.","Der Firmenwert ist der Betrag, den der Käufer über den beizulegenden Zeitwert des Nettovermögens hinaus gezahlt hat.","goodwill impairment|recognise goodwill","noun"],
["asset","Vermögenswert","Every asset on the balance sheet is funded either by debt or by equity.","Jeder Vermögenswert in der Bilanz ist entweder durch Fremd- oder Eigenkapital finanziert.","current assets|intangible asset","noun"],
["liability","Verbindlichkeit|Verpflichtung","Pension obligations are a long-term liability for the group.","Pensionsverpflichtungen sind eine langfristige Verbindlichkeit für den Konzern.","current liabilities|contingent liability","noun"],
["equity","Eigenkapital","Equity is what remains after subtracting liabilities from assets.","Eigenkapital ist das, was nach Abzug der Verbindlichkeiten vom Vermögen übrig bleibt.","shareholders equity|equity stake","noun"],
["retained earnings","Gewinnrücklagen","Retained earnings are profits kept in the business rather than paid out.","Gewinnrücklagen sind Gewinne, die im Unternehmen bleiben statt ausgeschüttet zu werden.","accumulated retained earnings|transfer to retained earnings","term"],
["working capital","Working Capital|Betriebskapital","A growing business ties up more cash in working capital.","Ein wachsendes Unternehmen bindet mehr Liquidität im Working Capital.","net working capital|working capital requirement","term","Current assets minus current liabilities — the cash tied up in running day-to-day operations."],
["inventory","Vorräte|Lagerbestand","Slow-moving inventory had to be written down at year end.","Langsam drehende Vorräte mussten zum Jahresende abgewertet werden.","inventory turnover|excess inventory","noun"],
["receivable","Forderung","Trade receivables rose because customers paid later than usual.","Die Forderungen aus Lieferungen und Leistungen stiegen, weil Kunden später zahlten als üblich.","accounts receivable|days receivable","noun"],
["payable","Verbindlichkeit aus Lieferungen und Leistungen","Stretching payables is a cheap but risky source of funding.","Das Strecken von Lieferantenverbindlichkeiten ist eine billige, aber riskante Finanzierungsquelle.","accounts payable|trade payables","noun"],
["provision","Rückstellung","The company set aside a provision for the pending lawsuit.","Das Unternehmen bildete eine Rückstellung für den anhängigen Rechtsstreit.","raise a provision|release a provision","noun"],
["write-off","Abschreibung|Ausbuchung","The write-off of the failed project hit fourth-quarter earnings.","Die Ausbuchung des gescheiterten Projekts belastete das Ergebnis des vierten Quartals.","one-off write-off|full write-off","noun"],
["deferred revenue","erhaltene Anzahlungen","Deferred revenue is cash collected for services not yet delivered.","Erhaltene Anzahlungen sind vereinnahmte Beträge für noch nicht erbrachte Leistungen.","release deferred revenue|deferred revenue balance","term","Cash already received for goods or services the company still owes the customer."],
["EBITDA","EBITDA|Ergebnis vor Zinsen, Steuern und Abschreibungen","EBITDA strips out financing and accounting choices to compare operations.","EBITDA blendet Finanzierungs- und Bilanzierungsentscheidungen aus, um das operative Geschäft vergleichbar zu machen.","adjusted EBITDA|EBITDA multiple","term","Earnings before interest, tax, depreciation and amortisation — a rough proxy for operating cash generation."],
["EBIT","EBIT|Betriebsergebnis","EBIT is operating profit before the capital structure is taken into account.","EBIT ist das operative Ergebnis, bevor die Kapitalstruktur berücksichtigt wird.","EBIT margin|normalised EBIT","term","Earnings before interest and tax — operating profit, independent of how the business is financed."],
["free cash flow","freier Cashflow","Free cash flow is what is left for investors after reinvestment.","Der freie Cashflow ist das, was nach Reinvestitionen für die Kapitalgeber übrig bleibt.","levered free cash flow|free cash flow yield","term","Operating cash flow minus capital expenditure — the cash actually available to fund investors."],
["capital expenditure","Investitionsausgaben","Capital expenditure was held below depreciation to protect cash.","Die Investitionsausgaben wurden unter den Abschreibungen gehalten, um Liquidität zu schonen.","capex|maintenance capital expenditure","term"],
["operating expense","Betriebsaufwand","Operating expenses include salaries, rent and marketing.","Betriebsaufwendungen umfassen Gehälter, Mieten und Marketing.","opex|operating expense ratio","term"],
["margin","Marge","Margins compressed as raw material prices climbed.","Die Margen schrumpften, als die Rohstoffpreise stiegen.","gross margin|margin expansion","noun"],
["disclosure","Offenlegung|Angabe","The disclosure in the notes explained the change in accounting policy.","Die Angabe im Anhang erläuterte die Änderung der Bilanzierungsmethode.","full disclosure|disclosure requirements","noun"],
["restate","korrigieren|neu darstellen","The auditor forced the group to restate two years of accounts.","Der Prüfer zwang den Konzern, zwei Jahresabschlüsse zu korrigieren.","restate earnings|restate the accounts","verb","To publish corrected versions of financial statements that were previously reported wrongly."],
["accrue","abgrenzen|auflaufen","Interest accrues monthly even if it is only paid at maturity.","Zinsen laufen monatlich auf, auch wenn sie erst bei Fälligkeit gezahlt werden.","accrue interest|accrued expenses","verb"],
["book value","Buchwert","The share traded well below its book value for most of the year.","Die Aktie notierte den Großteil des Jahres deutlich unter ihrem Buchwert.","book value per share|price to book value","term"],
["carrying amount","Bilanzwert|Buchwert","The carrying amount of the asset exceeded its recoverable amount.","Der Bilanzwert des Vermögenswerts überstieg seinen erzielbaren Betrag.","carrying amount of goodwill|reduce the carrying amount","term","The value at which an asset currently sits on the balance sheet, after depreciation and impairment."],
["fiscal year","Geschäftsjahr","Their fiscal year ends in March rather than December.","Ihr Geschäftsjahr endet im März statt im Dezember.","fiscal year end|full fiscal year","term"],
["line item","Einzelposten|Bilanzposten","Restructuring costs were shown as a separate line item.","Restrukturierungskosten wurden als gesonderter Einzelposten ausgewiesen.","separate line item|line item detail","term"],
["top line","Umsatz","Management is chasing top-line growth at the expense of margin.","Das Management verfolgt Umsatzwachstum auf Kosten der Marge.","top-line growth|drive the top line","term","Revenue — the first line of the income statement, before any costs."],
["bottom line","Endergebnis|Nettogewinn","Cost cuts flowed straight through to the bottom line.","Kostensenkungen schlugen direkt auf das Endergebnis durch.","hit the bottom line|protect the bottom line","term","Net profit — the last line of the income statement, after every cost."],
["solvent","zahlungsfähig|solvent","The group remained solvent only because the banks extended the facility.","Der Konzern blieb nur zahlungsfähig, weil die Banken die Kreditlinie verlängerten.","remain solvent|technically solvent","adjective"],
["accounting policy","Bilanzierungsmethode","A change in accounting policy makes the two years hard to compare.","Eine Änderung der Bilanzierungsmethode macht die beiden Jahre schwer vergleichbar.","apply an accounting policy|change in accounting policy","term"],
["intangible asset","immaterieller Vermögenswert","Brands and patents are intangible assets.","Marken und Patente sind immaterielle Vermögenswerte.","recognise an intangible asset|amortise intangible assets","term"],
["one-off","einmalig|Sondereffekt","Analysts adjusted for one-off items before valuing the business.","Analysten bereinigten um Sondereffekte, bevor sie das Unternehmen bewerteten.","one-off charge|one-off gain","adjective"],
["normalise","normalisieren|bereinigen","We normalise earnings to strip out the effect of the pandemic year.","Wir bereinigen das Ergebnis, um den Effekt des Pandemiejahres herauszurechnen.","normalise earnings|normalised EBITDA","verb","To adjust reported figures for unusual or one-off effects so periods can be compared fairly."],
];

// ---------------------------------------------------------------------------
// Corporate Finance — valuation
// ---------------------------------------------------------------------------

export const FIN_VALUATION: DomainEntry[] = [
["valuation","Bewertung","The valuation came in well below the seller's expectations.","Die Bewertung lag deutlich unter den Erwartungen des Verkäufers.","valuation range|standalone valuation","noun"],
["discounted cash flow","Discounted-Cashflow-Verfahren","A discounted cash flow model values a business on the cash it will generate.","Ein Discounted-Cashflow-Modell bewertet ein Unternehmen anhand der künftigen Zahlungsströme.","DCF|build a discounted cash flow","term","A valuation that projects future cash flows and discounts them back to a value today."],
["discount rate","Abzinsungssatz|Diskontsatz","A higher discount rate lowers the present value of future cash flows.","Ein höherer Abzinsungssatz senkt den Barwert künftiger Zahlungsströme.","apply a discount rate|risk-adjusted discount rate","term"],
["present value","Barwert","The present value of the payment is lower the further away it is.","Der Barwert der Zahlung ist umso niedriger, je weiter sie entfernt liegt.","net present value|present value factor","term"],
["net present value","Kapitalwert|Nettobarwert","A project with a positive net present value creates value.","Ein Projekt mit positivem Kapitalwert schafft Wert.","NPV|positive net present value","term","The present value of a project's cash inflows minus the investment required to get them."],
["internal rate of return","interner Zinsfuß","The fund targets an internal rate of return above twenty percent.","Der Fonds strebt einen internen Zinsfuß von über zwanzig Prozent an.","IRR|gross internal rate of return","term","The discount rate at which a project's net present value is exactly zero."],
["terminal value","Endwert|Restwert","Terminal value often accounts for most of a DCF valuation.","Der Endwert macht oft den größten Teil einer DCF-Bewertung aus.","terminal value assumption|perpetuity terminal value","term","The value assigned to all cash flows beyond the explicit forecast period."],
["perpetuity","ewige Rente","A perpetuity pays the same amount every year forever.","Eine ewige Rente zahlt jedes Jahr denselben Betrag, und zwar unbegrenzt.","perpetuity growth rate|value a perpetuity","noun"],
["cost of capital","Kapitalkosten","The project only makes sense if it returns more than the cost of capital.","Das Projekt lohnt sich nur, wenn es mehr abwirft als die Kapitalkosten.","weighted average cost of capital|cost of capital assumption","term"],
["cost of equity","Eigenkapitalkosten","Cost of equity is higher than cost of debt because shareholders rank last.","Die Eigenkapitalkosten sind höher als die Fremdkapitalkosten, weil Aktionäre zuletzt bedient werden.","estimate the cost of equity|implied cost of equity","term"],
["cost of debt","Fremdkapitalkosten","Rising rates pushed the cost of debt up by two points.","Steigende Zinsen trieben die Fremdkapitalkosten um zwei Punkte nach oben.","after-tax cost of debt|marginal cost of debt","term"],
["WACC","WACC|gewichtete durchschnittliche Kapitalkosten","WACC blends the cost of debt and equity by their weights in the capital structure.","Der WACC mischt Fremd- und Eigenkapitalkosten nach ihrem Anteil an der Kapitalstruktur.","WACC calculation|implied WACC","term","Weighted average cost of capital — the blended return a company must earn to satisfy all its investors."],
["enterprise value","Unternehmenswert","Enterprise value is what it would cost to buy the whole operating business.","Der Unternehmenswert ist das, was der Erwerb des gesamten operativen Geschäfts kosten würde.","enterprise value to EBITDA|bridge to enterprise value","term","The value of the entire business, debt and equity together, independent of how it is financed."],
["equity value","Eigenkapitalwert","Equity value is enterprise value less net debt.","Der Eigenkapitalwert ist der Unternehmenswert abzüglich der Nettoverschuldung.","equity value per share|implied equity value","term"],
["net debt","Nettoverschuldung","Net debt is gross borrowings minus cash on the balance sheet.","Die Nettoverschuldung ist die Bruttoverschuldung abzüglich der Barmittel in der Bilanz.","net debt position|net debt to EBITDA","term"],
["multiple","Multiplikator|Multiple","The business changed hands at nine times EBITDA, a full multiple.","Das Unternehmen wechselte zum Neunfachen des EBITDA den Besitzer, ein stolzer Multiplikator.","trading multiple|transaction multiple","noun"],
["comparable company","Vergleichsunternehmen","We screened for comparable companies of a similar size and geography.","Wir suchten nach Vergleichsunternehmen ähnlicher Größe und Region.","comparable company analysis|set of comparables","term"],
["precedent transaction","Vergleichstransaktion","Precedent transactions show what buyers actually paid in past deals.","Vergleichstransaktionen zeigen, was Käufer in früheren Deals tatsächlich gezahlt haben.","precedent transaction analysis|recent precedent transactions","term","An earlier comparable deal used as a benchmark for what a target should be worth."],
["fair value","beizulegender Zeitwert","The asset was written down to fair value at the reporting date.","Der Vermögenswert wurde zum Stichtag auf den beizulegenden Zeitwert abgewertet.","fair value measurement|fair value adjustment","term"],
["intrinsic value","innerer Wert","Value investors buy when price sits below intrinsic value.","Value-Investoren kaufen, wenn der Preis unter dem inneren Wert liegt.","estimate intrinsic value|intrinsic value per share","term"],
["assumption","Annahme","The valuation is only as good as the assumptions behind it.","Die Bewertung ist nur so gut wie die Annahmen, die ihr zugrunde liegen.","key assumption|challenge an assumption","noun"],
["sensitivity analysis","Sensitivitätsanalyse","A sensitivity analysis shows how value reacts to a change in growth.","Eine Sensitivitätsanalyse zeigt, wie der Wert auf eine Wachstumsänderung reagiert.","run a sensitivity analysis|sensitivity table","term"],
["scenario","Szenario","We modelled a base, an upside and a downside scenario.","Wir modellierten ein Basis-, ein Aufwärts- und ein Abwärtsszenario.","base case scenario|downside scenario","noun"],
["forecast period","Prognosezeitraum","Cash flows are modelled explicitly over a five-year forecast period.","Die Zahlungsströme werden über einen fünfjährigen Prognosezeitraum explizit modelliert.","explicit forecast period|extend the forecast period","term"],
["growth rate","Wachstumsrate","A one-point change in the growth rate moves the valuation sharply.","Eine Änderung der Wachstumsrate um einen Punkt verschiebt die Bewertung deutlich.","perpetual growth rate|compound growth rate","term"],
["payback period","Amortisationsdauer","The investment has a payback period of just under four years.","Die Investition hat eine Amortisationsdauer von knapp vier Jahren.","short payback period|calculate the payback period","term"],
["hurdle rate","Mindestrendite","Any project below the hurdle rate is rejected automatically.","Jedes Projekt unterhalb der Mindestrendite wird automatisch abgelehnt.","clear the hurdle rate|internal hurdle rate","term","The minimum return a project must promise before a company will fund it."],
["premium","Aufschlag|Prämie","The buyer paid a thirty percent premium to the undisturbed share price.","Der Käufer zahlte einen Aufschlag von dreißig Prozent auf den unbeeinflussten Aktienkurs.","control premium|pay a premium","noun"],
["accretive","wertsteigernd","The acquisition is accretive to earnings from the first full year.","Die Übernahme wirkt ab dem ersten vollen Jahr ergebnissteigernd.","accretive to earnings|immediately accretive","adjective","Describing a deal that increases the acquirer's earnings per share."],
["dilutive","verwässernd","Issuing new shares to fund the deal is dilutive in the short run.","Die Ausgabe neuer Aktien zur Finanzierung des Deals wirkt kurzfristig verwässernd.","dilutive to earnings|dilutive issuance","adjective","Describing a deal or share issue that reduces the acquirer's earnings per share."],
["standalone","eigenständig","We valued the division on a standalone basis before adding synergies.","Wir bewerteten die Sparte zunächst eigenständig, bevor wir Synergien einrechneten.","standalone basis|standalone value","adjective"],
["run-rate","hochgerechnet","Cost savings are quoted on a run-rate basis once fully implemented.","Kosteneinsparungen werden nach vollständiger Umsetzung hochgerechnet ausgewiesen.","run-rate savings|run-rate EBITDA","adjective","Expressed as if the current level of performance already applied for a full year."],
["benchmark","Vergleichsmaßstab|Benchmark","We benchmarked margins against the three closest peers.","Wir verglichen die Margen mit den drei nächsten Wettbewerbern.","benchmark against|industry benchmark","noun"],
["peer group","Vergleichsgruppe","The peer group was widened to include two US listed players.","Die Vergleichsgruppe wurde um zwei US-notierte Anbieter erweitert.","select a peer group|peer group multiple","term"],
["bridge","Überleitung","The bridge explains the move from enterprise value to equity value.","Die Überleitung erklärt den Weg vom Unternehmenswert zum Eigenkapitalwert.","valuation bridge|EBITDA bridge","noun","A step-by-step reconciliation showing how one figure turns into another."],
["haircut","Abschlag","We applied a haircut to management's revenue plan.","Wir nahmen einen Abschlag auf den Umsatzplan des Managements vor.","apply a haircut|significant haircut","noun","A deliberate reduction applied to a figure to allow for risk or optimism."],
["upside","Aufwärtspotenzial","There is meaningful upside if the new plant ramps on time.","Es besteht erhebliches Aufwärtspotenzial, wenn das neue Werk planmäßig hochläuft.","upside case|limited upside","noun"],
["downside","Abwärtsrisiko","The downside is protected by the long-term supply contracts.","Das Abwärtsrisiko ist durch die langfristigen Lieferverträge begrenzt.","downside risk|downside protection","noun"],
["implied","impliziert","The offer price implies a multiple of eleven times EBITDA.","Der Angebotspreis impliziert einen Multiplikator vom Elffachen des EBITDA.","implied multiple|implied valuation","adjective"],
];

// ---------------------------------------------------------------------------
// Corporate Finance — M&A and the deal process
// ---------------------------------------------------------------------------

export const FIN_DEALS: DomainEntry[] = [
["acquisition","Übernahme|Akquisition","The acquisition closed three months after signing.","Die Übernahme wurde drei Monate nach der Unterzeichnung vollzogen.","bolt-on acquisition|complete an acquisition","noun"],
["merger","Fusion|Zusammenschluss","The merger created the second largest player in the region.","Die Fusion schuf den zweitgrößten Anbieter der Region.","merger of equals|announce a merger","noun"],
["target","Zielunternehmen","The target rejected the first offer as inadequate.","Das Zielunternehmen lehnte das erste Angebot als unzureichend ab.","acquisition target|approach a target","noun"],
["bidder","Bieter","Three bidders made it through to the second round.","Drei Bieter kamen in die zweite Runde.","strategic bidder|preferred bidder","noun"],
["due diligence","Due Diligence|Sorgfaltsprüfung","Due diligence uncovered a gap in the pension provisions.","Die Due Diligence deckte eine Lücke bei den Pensionsrückstellungen auf.","commercial due diligence|conduct due diligence","term","The detailed investigation of a target's finances, contracts and risks before a deal is signed."],
["data room","Datenraum","All contracts were uploaded to the virtual data room.","Alle Verträge wurden in den virtuellen Datenraum hochgeladen.","virtual data room|open the data room","term","The controlled document repository bidders are given access to during a sale process."],
["letter of intent","Absichtserklärung","The letter of intent set out price and exclusivity.","Die Absichtserklärung legte Preis und Exklusivität fest.","sign a letter of intent|non-binding letter of intent","term"],
["term sheet","Term Sheet|Eckpunktepapier","The term sheet covers the key commercial points in two pages.","Das Eckpunktepapier fasst die wesentlichen kommerziellen Punkte auf zwei Seiten zusammen.","negotiate a term sheet|binding term sheet","term","A short document setting out the main commercial terms before full contracts are drafted."],
["closing","Vollzug|Closing","Closing is conditional on antitrust approval.","Der Vollzug steht unter dem Vorbehalt der kartellrechtlichen Genehmigung.","closing conditions|delayed closing","noun"],
["signing","Unterzeichnung","Six weeks passed between signing and closing.","Zwischen Unterzeichnung und Vollzug lagen sechs Wochen.","signing date|signing to closing","noun"],
["synergy","Synergie","The buyer justified the premium with cost synergies.","Der Käufer begründete den Aufschlag mit Kostensynergien.","revenue synergies|realise synergies","noun"],
["integration","Integration|Eingliederung","Poor integration destroys more value than a high purchase price.","Eine schlechte Integration vernichtet mehr Wert als ein hoher Kaufpreis.","post-merger integration|integration plan","noun","The work of combining an acquired business with the buyer after a deal closes."],
["divest","veräußern|abstoßen","The group divested its loss-making Asian operations.","Der Konzern veräußerte sein verlustbringendes Asiengeschäft.","divest a division|divest non-core assets","verb"],
["divestiture","Veräußerung","The divestiture freed up capital for the core business.","Die Veräußerung setzte Kapital für das Kerngeschäft frei.","announce a divestiture|forced divestiture","noun"],
["carve-out","Carve-out|Abspaltung","The carve-out required building a standalone finance function.","Der Carve-out erforderte den Aufbau einer eigenständigen Finanzfunktion.","carve-out financials|complex carve-out","noun","The separation of one part of a business so it can be sold as a standalone company."],
["spin-off","Abspaltung","Shareholders received shares in the spin-off directly.","Die Aktionäre erhielten Aktien der abgespaltenen Gesellschaft direkt.","tax-free spin-off|announce a spin-off","noun"],
["takeover","Übernahme","The hostile takeover was defeated by a rival bid.","Die feindliche Übernahme scheiterte an einem konkurrierenden Angebot.","hostile takeover|takeover defence","noun"],
["tender offer","Übernahmeangebot","The tender offer was open to all shareholders for four weeks.","Das Übernahmeangebot stand allen Aktionären vier Wochen offen.","launch a tender offer|accept a tender offer","term"],
["mandate","Mandat","The bank won the sell-side mandate after a competitive pitch.","Die Bank gewann das Verkaufsmandat nach einem Wettbewerbspitch.","sell-side mandate|win a mandate","noun"],
["pitch","Pitch|Präsentation","We pitched the transaction to the board in January.","Wir präsentierten die Transaktion dem Vorstand im Januar.","pitch book|pitch for a mandate","noun"],
["sell-side","Verkäuferseite","On the sell-side the adviser works for the seller.","Auf der Verkäuferseite arbeitet der Berater für den Verkäufer.","sell-side process|sell-side adviser","adjective"],
["buy-side","Käuferseite","Buy-side advisers help the acquirer set a walk-away price.","Käuferseitige Berater helfen dem Erwerber, eine Preisobergrenze festzulegen.","buy-side mandate|buy-side due diligence","adjective"],
["auction","Auktion|Bieterverfahren","A controlled auction usually raises the final price.","Ein kontrolliertes Bieterverfahren erhöht meist den Endpreis.","controlled auction|run an auction","noun"],
["exclusivity","Exklusivität","The seller granted six weeks of exclusivity to the leading bidder.","Der Verkäufer gewährte dem führenden Bieter sechs Wochen Exklusivität.","period of exclusivity|grant exclusivity","noun"],
["escrow","Treuhandkonto|Escrow","Part of the price was held in escrow against warranty claims.","Ein Teil des Kaufpreises wurde als Sicherheit für Gewährleistungsansprüche treuhänderisch hinterlegt.","escrow account|release from escrow","noun","Money held by a neutral third party until agreed conditions are met."],
["earn-out","Earn-out|erfolgsabhängiger Kaufpreisanteil","An earn-out ties part of the price to future performance.","Ein Earn-out koppelt einen Teil des Kaufpreises an die künftige Entwicklung.","earn-out payment|structure an earn-out","noun","A deferred part of the purchase price that is only paid if the target hits agreed targets."],
["warranty","Garantie|Gewährleistung","The seller gave limited warranties on the financial accounts.","Der Verkäufer gab beschränkte Garantien auf die Jahresabschlüsse.","breach of warranty|warranty claim","noun"],
["indemnity","Freistellung","The buyer obtained a specific indemnity for the tax dispute.","Der Käufer erhielt eine spezifische Freistellung für den Steuerstreit.","tax indemnity|claim under an indemnity","noun","A promise by the seller to reimburse the buyer for a specific identified risk."],
["covenant","Covenant|Vertragsklausel","The loan covenant caps net debt at three times EBITDA.","Die Kreditklausel begrenzt die Nettoverschuldung auf das Dreifache des EBITDA.","breach a covenant|financial covenant","noun","A binding condition in a loan agreement that the borrower must keep satisfying."],
["antitrust","Kartellrecht","Antitrust clearance took longer than the parties expected.","Die kartellrechtliche Freigabe dauerte länger als die Parteien erwartet hatten.","antitrust approval|antitrust review","noun"],
["regulatory approval","behördliche Genehmigung","The deal lapsed because regulatory approval never arrived.","Der Deal platzte, weil die behördliche Genehmigung nie erteilt wurde.","obtain regulatory approval|subject to regulatory approval","term"],
["break fee","Break Fee|Abbruchgebühr","A break fee compensates the buyer if the seller walks away.","Eine Break Fee entschädigt den Käufer, wenn der Verkäufer aussteigt.","pay a break fee|reverse break fee","term","A payment owed by one side if a signed deal collapses for reasons within its control."],
["stake","Beteiligung|Anteil","The founder retained a twenty percent stake after the sale.","Der Gründer behielt nach dem Verkauf eine Beteiligung von zwanzig Prozent.","controlling stake|minority stake","noun"],
["majority","Mehrheit","The fund acquired a majority in the family-owned business.","Der Fonds erwarb eine Mehrheit an dem Familienunternehmen.","majority shareholder|majority stake","noun"],
["minority","Minderheit","Minority shareholders were bought out at the same price.","Minderheitsaktionäre wurden zum selben Preis abgefunden.","minority interest|squeeze out the minority","noun"],
["consideration","Gegenleistung|Kaufpreis","The consideration was split between cash and shares.","Die Gegenleistung teilte sich in Bargeld und Aktien auf.","cash consideration|total consideration","noun","What the buyer actually gives in exchange for the target — cash, shares, or a mix."],
["purchase price","Kaufpreis","The purchase price was adjusted for net debt at closing.","Der Kaufpreis wurde zum Vollzug um die Nettoverschuldung angepasst.","purchase price adjustment|headline purchase price","term"],
["walk-away price","Preisobergrenze","The board fixed a walk-away price before the final round.","Der Vorstand legte vor der letzten Runde eine Preisobergrenze fest.","set a walk-away price|disciplined walk-away price","term","The maximum a buyer will pay, above which it will abandon the deal."],
["bolt-on","Zukauf|Bolt-on","A string of bolt-ons doubled the platform in three years.","Eine Reihe von Zukäufen verdoppelte die Plattform in drei Jahren.","bolt-on acquisition|small bolt-on","adjective","A small acquisition added onto an existing larger business."],
["platform","Plattform","The fund bought a platform and grew it by acquisition.","Der Fonds erwarb eine Plattform und ließ sie durch Zukäufe wachsen.","platform investment|build a platform","noun"],
["confidentiality agreement","Vertraulichkeitsvereinbarung","No information is shared before the confidentiality agreement is signed.","Vor Unterzeichnung der Vertraulichkeitsvereinbarung werden keine Informationen geteilt.","sign a confidentiality agreement|mutual confidentiality agreement","term"],
["information memorandum","Informationsmemorandum","The information memorandum presents the business to potential buyers.","Das Informationsmemorandum stellt das Unternehmen potenziellen Käufern vor.","draft an information memorandum|confidential information memorandum","term"],
["deal flow","Deal Flow|Strom an Transaktionsgelegenheiten","The team's deal flow improved once it focused on one sector.","Der Deal Flow des Teams verbesserte sich, sobald es sich auf einen Sektor konzentrierte.","strong deal flow|proprietary deal flow","term","The stream of investment opportunities an investor sees over time."],
["closing conditions","Vollzugsbedingungen","All closing conditions were satisfied by the end of June.","Alle Vollzugsbedingungen waren bis Ende Juni erfüllt.","satisfy closing conditions|customary closing conditions","term"],
];

// ---------------------------------------------------------------------------
// Corporate Finance — capital structure, debt and equity markets
// ---------------------------------------------------------------------------

export const FIN_CAPITAL: DomainEntry[] = [
["capital structure","Kapitalstruktur","The capital structure was refinanced with cheaper long-term debt.","Die Kapitalstruktur wurde mit günstigerem langfristigem Fremdkapital refinanziert.","optimal capital structure|change the capital structure","term"],
["leverage","Verschuldungsgrad|Leverage","Leverage magnifies both returns and losses.","Der Verschuldungsgrad verstärkt sowohl Renditen als auch Verluste.","high leverage|reduce leverage","noun","The use of borrowed money to increase the potential return on equity."],
["gearing","Verschuldungsgrad","Gearing fell as the company paid down its term loan.","Der Verschuldungsgrad sank, als das Unternehmen sein Darlehen tilgte.","net gearing|gearing ratio","noun"],
["senior debt","vorrangiges Fremdkapital","Senior debt is repaid before any other creditor.","Vorrangiges Fremdkapital wird vor allen anderen Gläubigern zurückgezahlt.","senior secured debt|senior debt facility","term"],
["subordinated debt","nachrangiges Fremdkapital","Subordinated debt carries a higher coupon for the extra risk.","Nachrangiges Fremdkapital trägt für das zusätzliche Risiko einen höheren Kupon.","issue subordinated debt|subordinated note","term"],
["mezzanine","Mezzanine|Mezzanine-Kapital","Mezzanine sits between senior debt and equity in the structure.","Mezzanine liegt in der Struktur zwischen vorrangigem Fremdkapital und Eigenkapital.","mezzanine financing|mezzanine tranche","noun","Hybrid funding that ranks below bank debt but above equity, priced accordingly."],
["tranche","Tranche|Teilbetrag","The loan was split into three tranches with different maturities.","Das Darlehen wurde in drei Tranchen mit unterschiedlichen Laufzeiten aufgeteilt.","senior tranche|drawdown a tranche","noun","One slice of a larger loan or bond issue, with its own terms, ranking and maturity."],
["coupon","Kupon|Zinskupon","The bond pays a fixed coupon of four percent.","Die Anleihe zahlt einen festen Kupon von vier Prozent.","fixed coupon|coupon payment","noun"],
["maturity","Fälligkeit|Laufzeit","The facility has a maturity of five years.","Die Kreditlinie hat eine Laufzeit von fünf Jahren.","extend the maturity|maturity date","noun"],
["principal","Nominalbetrag|Kapitalbetrag","Interest is charged on the outstanding principal only.","Zinsen werden nur auf den ausstehenden Kapitalbetrag berechnet.","repay the principal|principal amount","noun","The original sum borrowed, separate from the interest charged on it."],
["amortising loan","Tilgungsdarlehen","An amortising loan repays principal steadily over its life.","Ein Tilgungsdarlehen zahlt den Kapitalbetrag stetig über die Laufzeit zurück.","fully amortising loan|amortising term loan","term"],
["bullet repayment","endfällige Tilgung","A bullet repayment leaves the whole principal due at maturity.","Bei endfälliger Tilgung wird der gesamte Kapitalbetrag erst zur Fälligkeit fällig.","bullet maturity|bullet loan","term","A loan structure where nothing is repaid until the entire principal falls due at the end."],
["refinance","refinanzieren|umschulden","The group refinanced ahead of the maturity wall in 2027.","Der Konzern refinanzierte sich vor der Fälligkeitsmauer im Jahr 2027.","refinance a facility|refinance early","verb"],
["facility","Kreditlinie|Fazilität","The revolving credit facility remained undrawn all year.","Die revolvierende Kreditlinie blieb das ganze Jahr ungenutzt.","credit facility|committed facility","noun"],
["drawdown","Inanspruchnahme|Abruf","The first drawdown funded the acquisition in March.","Der erste Abruf finanzierte die Übernahme im März.","drawdown request|initial drawdown","noun"],
["restructuring","Restrukturierung","The restructuring converted part of the debt into equity.","Die Restrukturierung wandelte einen Teil der Schulden in Eigenkapital um.","debt restructuring|financial restructuring","noun"],
["insolvency","Insolvenz","Insolvency proceedings opened after the banks withdrew support.","Das Insolvenzverfahren wurde eröffnet, nachdem die Banken ihre Unterstützung entzogen.","file for insolvency|insolvency proceedings","noun"],
["creditor","Gläubiger","Creditors agreed to extend the maturities by two years.","Die Gläubiger stimmten einer Verlängerung der Laufzeiten um zwei Jahre zu.","secured creditor|creditor committee","noun"],
["collateral","Sicherheit","The inventory was pledged as collateral for the loan.","Die Vorräte wurden als Sicherheit für das Darlehen verpfändet.","pledge collateral|collateral value","noun","Assets a borrower pledges that the lender can seize if the loan is not repaid."],
["security","Besicherung","The lenders took security over the group's real estate.","Die Kreditgeber ließen sich das Immobilienvermögen des Konzerns besichern.","take security|security package","noun"],
["credit rating","Bonitätsbewertung|Rating","The downgrade of its credit rating raised borrowing costs.","Die Herabstufung des Ratings erhöhte die Finanzierungskosten.","investment grade credit rating|credit rating agency","term"],
["investment grade","Investment Grade|Anlagequalität","Only investment grade issuers can access that part of the market.","Nur Emittenten mit Investment-Grade-Rating haben Zugang zu diesem Marktsegment.","investment grade rating|fall below investment grade","term","A credit rating high enough to signal comparatively low default risk."],
["high yield","Hochzins|High Yield","High yield bonds pay more because the issuer is riskier.","Hochzinsanleihen zahlen mehr, weil der Emittent riskanter ist.","high yield bond|high yield market","term"],
["bond","Anleihe","The company issued a ten-year bond at par.","Das Unternehmen begab eine zehnjährige Anleihe zum Nennwert.","corporate bond|issue a bond","noun"],
["issuer","Emittent","The issuer must publish a prospectus before the offering.","Der Emittent muss vor dem Angebot einen Prospekt veröffentlichen.","frequent issuer|issuer default","noun"],
["underwrite","garantieren|übernehmen","Two banks underwrote the entire share issue.","Zwei Banken garantierten die gesamte Aktienemission.","underwrite an offering|fully underwritten","verb","To guarantee that an issue of shares or bonds will be placed, taking any unsold portion onto your own books."],
["initial public offering","Börsengang","The initial public offering valued the company at four billion.","Der Börsengang bewertete das Unternehmen mit vier Milliarden.","IPO|launch an initial public offering","term"],
["rights issue","Bezugsrechtsemission","The rights issue let existing shareholders keep their percentage.","Die Bezugsrechtsemission erlaubte den bestehenden Aktionären, ihren Anteil zu halten.","discounted rights issue|launch a rights issue","term","A share issue offered first to existing shareholders in proportion to their holdings."],
["placement","Platzierung","The private placement was completed with four institutional investors.","Die Privatplatzierung wurde mit vier institutionellen Investoren abgeschlossen.","private placement|accelerated placement","noun"],
["prospectus","Prospekt","The prospectus sets out every material risk of the offering.","Der Prospekt legt jedes wesentliche Risiko des Angebots dar.","approve a prospectus|prospectus liability","noun"],
["dividend","Dividende","The board proposed a dividend of one euro per share.","Der Vorstand schlug eine Dividende von einem Euro je Aktie vor.","cut the dividend|dividend policy","noun"],
["payout ratio","Ausschüttungsquote","A payout ratio above one means the dividend is not covered by earnings.","Eine Ausschüttungsquote über eins bedeutet, dass die Dividende nicht durch den Gewinn gedeckt ist.","target payout ratio|sustainable payout ratio","term"],
["share buyback","Aktienrückkauf","The share buyback returned surplus cash to investors.","Der Aktienrückkauf gab überschüssige Liquidität an die Investoren zurück.","announce a share buyback|share buyback programme","term"],
["leveraged buyout","Leveraged Buyout|fremdfinanzierte Übernahme","A leveraged buyout funds most of the price with debt on the target.","Ein Leveraged Buyout finanziert den Großteil des Preises mit Schulden beim Zielunternehmen.","LBO|classic leveraged buyout","term","An acquisition funded largely by borrowing, secured against the target's own assets and cash flow."],
["private equity","Private Equity|Beteiligungskapital","Private equity holds companies for roughly five years on average.","Private Equity hält Unternehmen im Schnitt etwa fünf Jahre.","private equity fund|private equity sponsor","term","Investment in companies that are not listed on a stock exchange, usually with a view to selling them on."],
["sponsor","Sponsor|Finanzinvestor","The sponsor injected fresh equity to fund the bolt-on.","Der Finanzinvestor schoss frisches Eigenkapital für den Zukauf nach.","financial sponsor|sponsor-backed","noun","The private equity firm that owns and financially backs a portfolio company."],
["carry","Carried Interest|Carry","The partners only earn carry once investors get their money back.","Die Partner verdienen erst Carry, wenn die Investoren ihr Geld zurückerhalten haben.","carried interest|earn carry","noun","The share of a fund's profits paid to its managers once investors have been repaid a minimum return."],
["exit","Exit|Ausstieg","A trade sale was the fastest available exit.","Ein Verkauf an einen strategischen Käufer war der schnellste verfügbare Exit.","exit route|plan an exit","noun"],
["holding period","Haltedauer","A longer holding period drags down the internal rate of return.","Eine längere Haltedauer drückt den internen Zinsfuß.","average holding period|extend the holding period","term"],
["hedge","absichern|Absicherung","The treasury team hedged the currency exposure with forwards.","Das Treasury sicherte das Währungsrisiko mit Termingeschäften ab.","hedge exposure|natural hedge","verb","To take an offsetting position that limits losses from an adverse price or rate move."],
["liquidity","Liquidität","Liquidity dried up when the credit markets closed.","Die Liquidität versiegte, als sich die Kreditmärkte schlossen.","liquidity position|liquidity risk","noun"],
];

// ---------------------------------------------------------------------------
// Corporate Finance — markets, ratios and corporate governance
// ---------------------------------------------------------------------------

export const FIN_MARKETS: DomainEntry[] = [
["shareholder","Aktionär|Anteilseigner","Shareholders voted down the remuneration report.","Die Aktionäre lehnten den Vergütungsbericht ab.","majority shareholder|shareholder approval","noun"],
["stakeholder","Interessengruppe|Stakeholder","Employees are a stakeholder group with no formal vote.","Mitarbeiter sind eine Interessengruppe ohne formales Stimmrecht.","key stakeholder|stakeholder interests","noun"],
["board","Vorstand|Aufsichtsrat","The board approved the transaction unanimously.","Das Gremium genehmigte die Transaktion einstimmig.","board approval|sit on the board","noun"],
["governance","Unternehmensführung|Governance","Weak governance was the main red flag in diligence.","Schwache Unternehmensführung war das größte Warnsignal in der Prüfung.","corporate governance|governance structure","noun"],
["earnings per share","Gewinn je Aktie","Earnings per share rose despite flat net income, thanks to buybacks.","Der Gewinn je Aktie stieg trotz unverändertem Nettogewinn dank Rückkäufen.","EPS|diluted earnings per share","term"],
["price-earnings ratio","Kurs-Gewinn-Verhältnis","The price-earnings ratio looks cheap against the sector average.","Das Kurs-Gewinn-Verhältnis wirkt gegenüber dem Sektordurchschnitt günstig.","P/E ratio|forward price-earnings ratio","term"],
["return on equity","Eigenkapitalrendite","Return on equity flatters companies that carry a lot of debt.","Die Eigenkapitalrendite schmeichelt Unternehmen mit hoher Verschuldung.","ROE|improve return on equity","term"],
["return on invested capital","Rendite auf das eingesetzte Kapital","Return on invested capital above the cost of capital creates value.","Eine Rendite auf das eingesetzte Kapital oberhalb der Kapitalkosten schafft Wert.","ROIC|sustained return on invested capital","term"],
["current ratio","Liquiditätsgrad","A current ratio below one signals a possible funding gap.","Ein Liquiditätsgrad unter eins signalisiert eine mögliche Finanzierungslücke.","calculate the current ratio|healthy current ratio","term"],
["interest cover","Zinsdeckungsgrad","Interest cover fell to two times after the rate rise.","Der Zinsdeckungsgrad fiel nach der Zinserhöhung auf das Zweifache.","interest cover ratio|minimum interest cover","term","How many times a company's operating profit covers its interest bill."],
["market capitalisation","Marktkapitalisierung","Market capitalisation is the share price times the number of shares.","Die Marktkapitalisierung ist der Aktienkurs multipliziert mit der Aktienanzahl.","market cap|large market capitalisation","term"],
["float","Streubesitz","Only thirty percent of the shares are in free float.","Nur dreißig Prozent der Aktien befinden sich im Streubesitz.","free float|increase the float","noun","The portion of a company's shares that is actually available for public trading."],
["listed","börsennotiert","The listed peer group trades on higher multiples.","Die börsennotierte Vergleichsgruppe wird zu höheren Multiplikatoren gehandelt.","publicly listed|listed company","adjective"],
["volatility","Volatilität|Schwankungsbreite","Volatility spiked around the earnings announcement.","Die Volatilität stieg rund um die Ergebnisveröffentlichung sprunghaft an.","implied volatility|market volatility","noun"],
["exposure","Risiko|Engagement","The bank reduced its exposure to the property sector.","Die Bank reduzierte ihr Engagement im Immobiliensektor.","currency exposure|reduce exposure","noun","The amount a party stands to lose if a particular market or counterparty moves against it."],
["counterparty","Vertragspartner|Gegenpartei","Counterparty risk rose as the broker's rating slipped.","Das Gegenparteirisiko stieg, als das Rating des Brokers nachgab.","counterparty risk|approved counterparty","noun"],
["arbitrage","Arbitrage|Ausnutzung von Preisunterschieden","Arbitrage closes price gaps between two identical assets.","Arbitrage schließt Preislücken zwischen zwei identischen Vermögenswerten.","risk arbitrage|arbitrage opportunity","noun","Profiting from a price difference for the same asset in two markets, with little or no risk."],
["spread","Spread|Aufschlag","The credit spread widened by eighty basis points.","Der Kreditaufschlag weitete sich um achtzig Basispunkte aus.","credit spread|spread widening","noun","The difference between two rates or prices, usually the extra yield paid for taking on risk."],
["basis point","Basispunkt","One hundred basis points equal one percentage point.","Einhundert Basispunkte entsprechen einem Prozentpunkt.","fifty basis points|basis point move","term","One hundredth of a percentage point, the standard unit for quoting rate changes."],
["benchmark rate","Referenzzinssatz","The loan is priced at the benchmark rate plus a margin.","Das Darlehen wird zum Referenzzinssatz zuzüglich einer Marge verzinst.","floating benchmark rate|benchmark rate reform","term"],
["inflation","Inflation|Geldentwertung","Inflation eroded the real value of the fixed payments.","Die Inflation zehrte den realen Wert der festen Zahlungen auf.","headline inflation|inflation expectations","noun","A general rise in the price level, which reduces what one unit of currency buys."],
["real terms","real|preisbereinigt","In real terms, revenue was flat once inflation is stripped out.","Real betrachtet stagnierte der Umsatz, sobald die Inflation herausgerechnet wird.","in real terms|real growth","term","Measured after adjusting for inflation, as opposed to nominal figures."],
["par","Nennwert|pari","The bond was issued at par and later traded above it.","Die Anleihe wurde zum Nennwert begeben und später darüber gehandelt.","at par|below par","noun","The face value of a bond, the amount repaid at maturity."],
["portfolio","Portfolio|Bestand","The portfolio was rebalanced towards defensive sectors.","Das Portfolio wurde in Richtung defensiver Sektoren umgeschichtet.","diversified portfolio|portfolio company","noun","The whole collection of investments or businesses held by one investor."],
["diversification","Diversifikation|Streuung","Diversification reduces risk without necessarily reducing return.","Diversifikation senkt das Risiko, ohne zwangsläufig die Rendite zu senken.","geographic diversification|benefit of diversification","noun"],
["due date","Fälligkeitstermin","The interest due date falls on the last day of each quarter.","Der Zinsfälligkeitstermin fällt auf den letzten Tag jedes Quartals.","original due date|miss the due date","term"],
["quarter","Quartal","Results beat expectations in the second quarter.","Die Ergebnisse übertrafen im zweiten Quartal die Erwartungen.","first quarter|quarter on quarter","noun"],
["guidance","Prognose|Ausblick","Management raised full-year guidance after a strong summer.","Das Management hob nach einem starken Sommer die Jahresprognose an.","issue guidance|withdraw guidance","noun","A company's own published forecast of its coming financial performance."],
["headwind","Gegenwind","Currency was a headwind of two points on reported growth.","Währungseffekte bremsten das ausgewiesene Wachstum um zwei Punkte.","face headwinds|currency headwind","noun","A factor working against a company's performance."],
["tailwind","Rückenwind","Falling input costs were a welcome tailwind for margins.","Sinkende Vorleistungskosten waren ein willkommener Rückenwind für die Margen.","structural tailwind|enjoy a tailwind","noun","A factor working in favour of a company's performance."],
];

// ---------------------------------------------------------------------------
// Mathematical English — arithmetic and how expressions are read aloud
// ---------------------------------------------------------------------------

export const MATH_OPERATIONS: DomainEntry[] = [
["sum","Summe","The sum of the first ten integers is fifty-five.","Die Summe der ersten zehn ganzen Zahlen ist fünfundfünfzig.","sum of|running sum","noun"],
["difference","Differenz","The difference between the two figures is negligible.","Die Differenz zwischen den beiden Werten ist vernachlässigbar.","take the difference|difference between","noun"],
["product","Produkt","The product of three and four is twelve.","Das Produkt aus drei und vier ist zwölf.","product of|cross product","noun"],
["quotient","Quotient|Ergebnis einer Division","Dividing revenue by headcount gives the quotient we need.","Die Division des Umsatzes durch die Mitarbeiterzahl ergibt den gesuchten Quotienten.","quotient of|resulting quotient","noun","The result of dividing one number by another."],
["numerator","Zähler","The numerator sits above the line in a fraction.","Der Zähler steht in einem Bruch über dem Strich.","numerator and denominator|increase the numerator","noun"],
["denominator","Nenner","If the denominator grows faster, the ratio falls.","Wenn der Nenner schneller wächst, sinkt das Verhältnis.","common denominator|denominator effect","noun"],
["fraction","Bruch","Write the result as a fraction rather than a decimal.","Schreibe das Ergebnis als Bruch statt als Dezimalzahl.","simplify a fraction|proper fraction","noun"],
["decimal","Dezimalzahl","Round the decimal to two places.","Runde die Dezimalzahl auf zwei Stellen.","decimal place|two decimal points","noun"],
["remainder","Rest","Seventeen divided by five is three, remainder two.","Siebzehn geteilt durch fünf ist drei, Rest zwei.","leave a remainder|remainder of","noun"],
["divide","teilen|dividieren","Divide both sides by three to isolate the variable.","Teile beide Seiten durch drei, um die Variable zu isolieren.","divide by|divide evenly","verb"],
["subtract","subtrahieren|abziehen","Subtract the cost base from revenue to get gross profit.","Ziehe die Kostenbasis vom Umsatz ab, um den Rohertrag zu erhalten.","subtract from|subtract the mean","verb"],
["round","runden","Round the figure to the nearest thousand.","Runde den Wert auf den nächsten Tausender.","round to|round the result","verb"],
["round up","aufrunden","Round up whenever the next digit is five or more.","Runde auf, sobald die nächste Ziffer fünf oder größer ist.","round up to|always round up","term"],
["round down","abrunden","We round down to stay conservative in the model.","Wir runden ab, um im Modell konservativ zu bleiben.","round down to|round down the estimate","term"],
["square","quadrieren","Square the deviation before you average it.","Quadriere die Abweichung, bevor du sie mittelst.","square the difference|square both sides","verb"],
["squared","zum Quadrat|hoch zwei","Read x squared as x to the power of two.","Lies x zum Quadrat als x hoch zwei.","x squared|squared error","adjective","Raised to the power of two — how you say a superscript 2 out loud."],
["square root","Quadratwurzel","The square root of eighty-one is nine.","Die Quadratwurzel aus einundachtzig ist neun.","take the square root|square root of","term"],
["cube root","Kubikwurzel","The cube root of twenty-seven is three.","Die Kubikwurzel aus siebenundzwanzig ist drei.","cube root of|take the cube root","term"],
["exponent","Exponent|Hochzahl","A negative exponent means one over the positive power.","Ein negativer Exponent bedeutet eins geteilt durch die positive Potenz.","negative exponent|exponent rules","noun","The small raised number saying how many times a base is multiplied by itself."],
["power","Potenz","Two to the power of ten is one thousand and twenty-four.","Zwei hoch zehn ist eintausendvierundzwanzig.","to the power of|raise to a power","noun"],
["to the power of","hoch","Read the notation as three to the power of four.","Lies die Schreibweise als drei hoch vier.","x to the power of n|raised to the power of","term","The spoken form of a superscript: three to the power of four means three with an exponent of four."],
["logarithm","Logarithmus","Taking the logarithm turns a product into a sum.","Das Logarithmieren verwandelt ein Produkt in eine Summe.","natural logarithm|logarithm of","noun"],
["absolute value","Betrag|Absolutwert","The absolute value of minus seven is seven.","Der Betrag von minus sieben ist sieben.","absolute value of|take the absolute value","term"],
["integer","ganze Zahl","The answer has to be an integer, so we cannot round to a half.","Die Antwort muss eine ganze Zahl sein, also können wir nicht auf eine Hälfte runden.","positive integer|nearest integer","noun"],
["even number","gerade Zahl","Every even number is divisible by two.","Jede gerade Zahl ist durch zwei teilbar.","an even number of|even number of periods","term"],
["odd number","ungerade Zahl","With an odd number of observations the median is a real data point.","Bei einer ungeraden Anzahl von Beobachtungen ist der Median ein echter Datenpunkt.","an odd number of|odd number of terms","term"],
["reciprocal","Kehrwert","The reciprocal of four is one quarter.","Der Kehrwert von vier ist ein Viertel.","take the reciprocal|reciprocal of","noun"],
["order of magnitude","Größenordnung","The two estimates differ by an order of magnitude.","Die beiden Schätzungen unterscheiden sich um eine Größenordnung.","same order of magnitude|order of magnitude larger","term","A factor of roughly ten — used to compare how big two numbers are in rough terms."],
["approximate","annähern|schätzen","We approximate the curve with a straight line over short intervals.","Wir nähern die Kurve über kurze Intervalle mit einer Geraden an.","approximate the value|closely approximate","verb"],
];

// ---------------------------------------------------------------------------
// Mathematical English — algebra, functions and calculus
// ---------------------------------------------------------------------------

export const MATH_ALGEBRA: DomainEntry[] = [
["equation","Gleichung","Set the two expressions equal and solve the equation.","Setze die beiden Ausdrücke gleich und löse die Gleichung.","solve an equation|linear equation","noun"],
["formula","Formel","The formula holds only when the growth rate is below the discount rate.","Die Formel gilt nur, wenn die Wachstumsrate unter dem Abzinsungssatz liegt.","apply a formula|derive a formula","noun"],
["variable","Variable|Veränderliche","Treat price as the variable and hold volume fixed.","Behandle den Preis als Variable und halte die Menge fest.","independent variable|dependent variable","noun","A quantity in an equation that is allowed to take different values."],
["constant","Konstante","Everything else is treated as a constant in this step.","Alles andere wird in diesem Schritt als Konstante behandelt.","hold constant|constant term","noun","A quantity in an equation that keeps the same value while the variables change."],
["coefficient","Koeffizient","The coefficient on price tells us how sensitive demand is.","Der Koeffizient beim Preis zeigt, wie empfindlich die Nachfrage reagiert.","regression coefficient|estimated coefficient","noun"],
["expression","Ausdruck","Simplify the expression before substituting any numbers.","Vereinfache den Ausdruck, bevor du Zahlen einsetzt.","algebraic expression|simplify an expression","noun"],
["solve for","auflösen nach","Solve for x by moving every other term to the right.","Löse nach x auf, indem du alle anderen Terme nach rechts bringst.","solve for x|solve for the unknown","term"],
["rearrange","umstellen","Rearrange the formula to make growth the subject.","Stelle die Formel so um, dass das Wachstum allein steht.","rearrange the equation|rearrange for","verb"],
["factor out","ausklammern","Factor out the common term to see the structure.","Klammere den gemeinsamen Term aus, um die Struktur zu erkennen.","factor out a term|factor out the constant","term"],
["cancel out","sich aufheben|kürzen","The two effects cancel out almost exactly.","Die beiden Effekte heben sich nahezu exakt auf.","cancel out the terms|effects cancel out","term"],
["inequality","Ungleichung","The inequality holds for every positive value of x.","Die Ungleichung gilt für jeden positiven Wert von x.","solve an inequality|strict inequality","noun"],
["linear","linear|geradlinig","Costs are linear in volume above the break-even point.","Die Kosten verlaufen oberhalb des Break-even linear zur Menge.","linear relationship|linear growth","adjective","Changing by a constant amount for each step, so the graph is a straight line."],
["exponential","exponentiell","Compounding makes the curve exponential rather than straight.","Der Zinseszins macht die Kurve exponentiell statt gerade.","exponential growth|exponential decay","adjective"],
["quadratic","quadratisch","A quadratic equation has at most two real solutions.","Eine quadratische Gleichung hat höchstens zwei reelle Lösungen.","quadratic equation|quadratic formula","adjective"],
["function","Funktion","Write profit as a function of price and volume.","Schreibe den Gewinn als Funktion von Preis und Menge.","function of|continuous function","noun"],
["slope","Steigung","The slope of the line gives the cost per additional unit.","Die Steigung der Geraden gibt die Kosten je zusätzlicher Einheit an.","slope of the line|steep slope","noun"],
["intercept","Achsenabschnitt","The intercept is the fixed cost when volume is zero.","Der Achsenabschnitt entspricht den Fixkosten bei einer Menge von null.","y-intercept|estimated intercept","noun"],
["derivative","Ableitung","The derivative measures how fast the function is changing.","Die Ableitung misst, wie schnell sich die Funktion ändert.","first derivative|take the derivative","noun"],
["integral","Integral|Stammfunktion","The integral gives the area under the curve.","Das Integral ergibt die Fläche unter der Kurve.","definite integral|evaluate the integral","noun","The mathematical operation that sums a function over a range, giving the area under its curve."],
["limit","Grenzwert","As n grows without bound, the limit approaches one.","Wenn n unbegrenzt wächst, nähert sich der Grenzwert eins.","limit of|in the limit","noun","The value a function or sequence gets arbitrarily close to as its input approaches some point."],
["matrix","Matrix|Zahlenschema","Store the coefficients in a three by three matrix.","Speichere die Koeffizienten in einer Drei-mal-drei-Matrix.","invert a matrix|covariance matrix","noun","A rectangular grid of numbers arranged in rows and columns."],
["vector","Vektor","Each row of the table is treated as a vector.","Jede Zeile der Tabelle wird als Vektor behandelt.","column vector|vector of weights","noun"],
["proportional","proportional|verhältnisgleich","Revenue is proportional to volume at a constant price.","Der Umsatz ist bei konstantem Preis proportional zur Menge.","directly proportional|proportional to","adjective","Changing by the same factor as another quantity: double one and the other doubles too."],
["inversely proportional","umgekehrt proportional","Present value is inversely proportional to the discount rate.","Der Barwert ist umgekehrt proportional zum Abzinsungssatz.","inversely proportional to|roughly inversely proportional","term","Growing when the other quantity shrinks: double one and the other halves."],
["hold constant","konstant halten","Hold volume constant and vary price alone.","Halte die Menge konstant und variiere allein den Preis.","hold everything else constant|hold the rate constant","term"],
["asymptote","Asymptote|Grenzgerade","The curve approaches the asymptote without ever touching it.","Die Kurve nähert sich der Asymptote, ohne sie je zu berühren.","horizontal asymptote|approach an asymptote","noun","A line that a curve gets ever closer to without ever reaching it."],
];

// ---------------------------------------------------------------------------
// Mathematical English — statistics and probability
// ---------------------------------------------------------------------------

export const MATH_STATS: DomainEntry[] = [
["mean","Mittelwert|Durchschnitt","The mean is pulled upwards by a handful of large values.","Der Mittelwert wird von einer Handvoll großer Werte nach oben gezogen.","arithmetic mean|sample mean","noun"],
["median","Median|Zentralwert","The median is more robust to outliers than the mean.","Der Median ist gegenüber Ausreißern robuster als der Mittelwert.","median value|median household","noun","The middle value once all observations are put in order."],
["standard deviation","Standardabweichung","A high standard deviation means the values are widely spread.","Eine hohe Standardabweichung bedeutet, dass die Werte weit gestreut sind.","one standard deviation|sample standard deviation","term"],
["variance","Varianz","Variance is the square of the standard deviation.","Die Varianz ist das Quadrat der Standardabweichung.","explained variance|variance of returns","noun"],
["distribution","Verteilung","The distribution of returns has a long left tail.","Die Verteilung der Renditen hat einen langen linken Rand.","probability distribution|skewed distribution","noun"],
["normal distribution","Normalverteilung","Under a normal distribution, two thirds lie within one standard deviation.","Bei einer Normalverteilung liegen zwei Drittel innerhalb einer Standardabweichung.","assume a normal distribution|standard normal distribution","term"],
["probability","Wahrscheinlichkeit","The probability of both events happening is the product of the two.","Die Wahrscheinlichkeit, dass beide Ereignisse eintreten, ist das Produkt der beiden.","conditional probability|probability of default","noun"],
["sample","Stichprobe","A sample of thirty is too small to draw firm conclusions.","Eine Stichprobe von dreißig ist zu klein für belastbare Schlüsse.","random sample|sample size","noun"],
["population","Grundgesamtheit","The sample should look like the population it is drawn from.","Die Stichprobe sollte der Grundgesamtheit ähneln, aus der sie stammt.","entire population|population mean","noun"],
["correlation","Korrelation","A correlation close to one means the two move almost together.","Eine Korrelation nahe eins bedeutet, dass sich beide fast gleich bewegen.","strong correlation|correlation coefficient","noun"],
["causation","Kausalität","Correlation does not establish causation.","Korrelation begründet keine Kausalität.","imply causation|reverse causation","noun"],
["regression","Regression|Ausgleichsrechnung","The regression explains sixty percent of the variation.","Die Regression erklärt sechzig Prozent der Streuung.","linear regression|run a regression","noun","A statistical method that fits a line through data to explain one variable by others."],
["outlier","Ausreißer","We excluded the outlier before fitting the line.","Wir schlossen den Ausreißer aus, bevor wir die Gerade anpassten.","remove an outlier|extreme outlier","noun"],
["skew","Schiefe","A few enormous deals skew the average deal size upwards.","Einige riesige Transaktionen verzerren die durchschnittliche Dealgröße nach oben.","right skew|skew the results","noun"],
["confidence interval","Konfidenzintervall","The confidence interval is wide because the sample is small.","Das Konfidenzintervall ist breit, weil die Stichprobe klein ist.","ninety-five percent confidence interval|narrow confidence interval","term","A range that is likely to contain the true value, given a stated level of certainty."],
["significance","Signifikanz","The result cleared the usual threshold for statistical significance.","Das Ergebnis überschritt die übliche Schwelle für statistische Signifikanz.","statistical significance|level of significance","noun"],
["hypothesis","Hypothese","The data does not reject the null hypothesis.","Die Daten verwerfen die Nullhypothese nicht.","null hypothesis|test a hypothesis","noun"],
["weighted average","gewichteter Durchschnitt","Use a weighted average so large positions count more.","Verwende einen gewichteten Durchschnitt, damit große Positionen stärker zählen.","calculate a weighted average|weighted average cost","term"],
["compound annual growth rate","durchschnittliche jährliche Wachstumsrate","The compound annual growth rate smooths out the volatile years.","Die durchschnittliche jährliche Wachstumsrate glättet die schwankenden Jahre.","CAGR|five-year compound annual growth rate","term","The single constant yearly rate that would take a value from its start point to its end point."],
["percentile","Perzentil","The firm sits in the top percentile for margin.","Das Unternehmen liegt bei der Marge im obersten Perzentil.","ninetieth percentile|percentile rank","noun"],
["quartile","Quartil","Only the bottom quartile lost money last year.","Nur das unterste Quartil machte im letzten Jahr Verluste.","top quartile|upper quartile","noun"],
["frequency","Häufigkeit","Plot the frequency of each outcome as a histogram.","Trage die Häufigkeit jedes Ergebnisses als Histogramm auf.","relative frequency|frequency distribution","noun"],
["bias","Verzerrung|Bias","Survivorship bias makes historical returns look better than they were.","Der Survivorship Bias lässt historische Renditen besser aussehen, als sie waren.","selection bias|correct for bias","noun","A systematic error that pushes results consistently in one direction."],
["random","zufällig","Draw a random subset rather than the first fifty rows.","Ziehe eine zufällige Teilmenge statt der ersten fünfzig Zeilen.","random sample|purely random","adjective"],
["margin of error","Fehlerspanne","The lead is inside the margin of error.","Der Vorsprung liegt innerhalb der Fehlerspanne.","within the margin of error|reduce the margin of error","term"],
["dispersion","Streuung","Dispersion across the peer group widened after the shock.","Die Streuung innerhalb der Vergleichsgruppe nahm nach dem Schock zu.","measure of dispersion|high dispersion","noun"],
["data point","Datenpunkt","One data point is an anecdote, not a trend.","Ein einzelner Datenpunkt ist eine Anekdote, kein Trend.","single data point|missing data point","term"],
["trend line","Trendlinie","The trend line flattens in the last two periods.","Die Trendlinie flacht in den letzten beiden Perioden ab.","fit a trend line|underlying trend line","term"],
["histogram","Histogramm","The histogram shows most values clustered near the middle.","Das Histogramm zeigt, dass sich die meisten Werte um die Mitte ballen.","plot a histogram|histogram bin","noun"],
];

// ---------------------------------------------------------------------------
// Mathematical English — describing data, charts and change
// ---------------------------------------------------------------------------

export const MATH_DESCRIBING: DomainEntry[] = [
["axis","Achse","Time runs along the horizontal axis.","Die Zeit verläuft entlang der waagerechten Achse.","horizontal axis|label the axis","noun"],
["horizontal axis","waagerechte Achse|x-Achse","Put the periods on the horizontal axis.","Trage die Perioden auf der waagerechten Achse ab.","along the horizontal axis|horizontal axis label","term"],
["vertical axis","senkrechte Achse|y-Achse","The vertical axis does not start at zero, which exaggerates the move.","Die senkrechte Achse beginnt nicht bei null, was die Bewegung übertreibt.","on the vertical axis|vertical axis scale","term"],
["plot","auftragen|einzeichnen","Plot revenue against headcount to see the relationship.","Trage den Umsatz gegen die Mitarbeiterzahl auf, um den Zusammenhang zu sehen.","plot against|plot the data","verb"],
["chart","Diagramm|Schaubild","The chart makes the seasonal pattern obvious.","Das Diagramm macht das saisonale Muster offensichtlich.","read a chart|chart shows","noun"],
["bar chart","Balkendiagramm","A bar chart compares categories better than a line does.","Ein Balkendiagramm vergleicht Kategorien besser als eine Linie.","stacked bar chart|draw a bar chart","term"],
["line graph","Liniendiagramm","The line graph tracks the balance month by month.","Das Liniendiagramm verfolgt den Saldo Monat für Monat.","plot a line graph|line graph shows","term"],
["peak","Höchststand|Spitze","Volumes reached their peak in the third quarter.","Die Volumina erreichten ihren Höchststand im dritten Quartal.","reach a peak|peak level","noun"],
["trough","Tiefpunkt","Prices bottomed out at the trough in early spring.","Die Preise erreichten ihren Tiefpunkt im Frühjahr.","hit the trough|peak to trough","noun"],
["plateau","Plateau|Hochebene","Growth hit a plateau after the second year.","Das Wachstum erreichte nach dem zweiten Jahr ein Plateau.","reach a plateau|long plateau","noun","A stretch where a series stops rising or falling and stays roughly level."],
["percentage point","Prozentpunkt","The margin improved by two percentage points, not two percent.","Die Marge verbesserte sich um zwei Prozentpunkte, nicht um zwei Prozent.","by two percentage points|percentage point gap","term","The arithmetic difference between two percentages — moving from 10% to 12% is two percentage points."],
["year on year","im Jahresvergleich","Sales were up eight percent year on year.","Der Umsatz lag im Jahresvergleich acht Prozent höher.","year on year growth|compare year on year","term","Comparing a period with the same period twelve months earlier."],
["compound","aufzinsen|verzinsen","Interest compounds monthly rather than annually.","Die Zinsen werden monatlich statt jährlich aufgezinst.","compound interest|compound monthly","verb","To let a return build on itself, so each period earns a return on the previous gains as well."],
["double","verdoppeln","Volumes doubled between the first and last year.","Die Volumina verdoppelten sich zwischen dem ersten und dem letzten Jahr.","double in size|more than double","verb"],
["halve","halbieren","The unit cost halved as the plant reached full capacity.","Die Stückkosten halbierten sich, als das Werk die volle Auslastung erreichte.","halve the cost|roughly halve","verb"],
["ratio","Verhältnis|Kennzahl","Express the two figures as a ratio rather than absolute numbers.","Drücke die beiden Werte als Verhältnis statt in absoluten Zahlen aus.","debt to equity ratio|calculate a ratio","noun"],
["proportion","Anteil","A growing proportion of revenue comes from subscriptions.","Ein wachsender Anteil des Umsatzes stammt aus Abonnements.","a large proportion of|in proportion to","noun"],
["rate of change","Änderungsrate","The rate of change slowed even though the level kept rising.","Die Änderungsrate verlangsamte sich, obwohl das Niveau weiter stieg.","rate of change slows|underlying rate of change","term"],
["threshold","Schwellenwert","Anything above that threshold triggers a second review.","Alles oberhalb dieses Schwellenwerts löst eine zweite Prüfung aus.","cross a threshold|threshold value","noun"],
["magnitude","Ausmaß|Größe","The magnitude of the swing surprised the whole desk.","Das Ausmaß des Ausschlags überraschte den gesamten Handelstisch.","order of magnitude|magnitude of the change","noun"],
["rounding error","Rundungsfehler","The gap is a rounding error, not a real discrepancy.","Die Lücke ist ein Rundungsfehler, keine echte Abweichung.","within rounding error|accumulate rounding errors","term"],
["scale","Skala|Maßstab","The chart uses a logarithmic scale to fit both series.","Das Diagramm verwendet eine logarithmische Skala, um beide Reihen abzubilden.","logarithmic scale|change the scale","noun"],
["flat","unverändert|flach","Revenue was flat despite the extra marketing spend.","Der Umsatz blieb trotz der zusätzlichen Marketingausgaben unverändert.","broadly flat|flat year on year","adjective"],
["offsetting","gegenläufig|ausgleichend","The two offsetting effects left the total unchanged.","Die beiden gegenläufigen Effekte ließen die Gesamtsumme unverändert.","offsetting effect|largely offsetting","adjective"],
["net of","abzüglich","The figure is quoted net of tax and fees.","Der Wert wird abzüglich Steuern und Gebühren angegeben.","net of tax|net of costs","term","After subtracting the stated item — net of tax means the tax has already been deducted."],
];
