// Raw general-vocabulary nouns: [en, de (pipe-separated), enSentence, deSentence, collocations (pipe-separated)]
// Same RawEntry shape as vocab-raw.ts; kept in its own file since it's a distinct content batch
// (200 everyday/business nouns) added to expand the general Vocabulary track.
import type { RawEntry } from "./vocab-raw";

export const N1: RawEntry[] = [
["achievement","Errungenschaft|Leistung","Winning the award was a major achievement for the team.","Die Auszeichnung zu gewinnen war eine große Errungenschaft für das Team.","a major achievement|proud of an achievement"],
["acquaintance","Bekannte(r)|Bekanntschaft","She met an old acquaintance at the conference.","Sie traf auf der Konferenz eine alte Bekannte.","a mutual acquaintance|make someone's acquaintance"],
["agenda","Tagesordnung|Agenda","The next item on the agenda is the budget review.","Der nächste Punkt auf der Tagesordnung ist die Budgetüberprüfung.","set the agenda|hidden agenda"],
["aisle","Gang","The bread is in the third aisle.","Das Brot ist im dritten Gang.","walk down the aisle|grocery aisle"],
["ambition","Ehrgeiz|Ambition","His ambition is to lead the department within five years.","Sein Ehrgeiz ist es, die Abteilung innerhalb von fünf Jahren zu leiten.","fulfil an ambition|driven by ambition"],
["amenity","Annehmlichkeit|Ausstattung","The hotel offers amenities like a gym and a pool.","Das Hotel bietet Annehmlichkeiten wie ein Fitnessstudio und einen Pool.","modern amenities|local amenities"],
["anecdote","Anekdote","He told an anecdote about his first job interview.","Er erzählte eine Anekdote über sein erstes Vorstellungsgespräch.","share an anecdote|amusing anecdote"],
["appliance","Gerät|Haushaltsgerät","They bought a new kitchen appliance last week.","Sie kauften letzte Woche ein neues Küchengerät.","household appliance|electrical appliance"],
["appointment","Termin","I have a doctor's appointment at three o'clock.","Ich habe um drei Uhr einen Arzttermin.","make an appointment|cancel an appointment"],
["apprenticeship","Ausbildung|Lehre","He completed a three-year apprenticeship as an electrician.","Er absolvierte eine dreijährige Ausbildung als Elektriker.","start an apprenticeship|complete an apprenticeship"],
["aptitude","Begabung|Eignung","She has a natural aptitude for languages.","Sie hat eine natürliche Begabung für Sprachen.","aptitude for numbers|aptitude test"],
["arrangement","Vereinbarung|Arrangement","We came to an arrangement that suited both parties.","Wir trafen eine Vereinbarung, die beiden Parteien zusagte.","reach an arrangement|financial arrangement"],
["artifact","Artefakt","The museum displays artifacts from ancient Rome.","Das Museum zeigt Artefakte aus dem antiken Rom.","ancient artifact|cultural artifact"],
["aspiration","Bestrebung|Wunsch","Her aspiration is to start her own business one day.","Ihr Wunsch ist es, eines Tages ein eigenes Unternehmen zu gründen.","career aspiration|high aspirations"],
["assignment","Aufgabe|Auftrag","She finished the assignment ahead of schedule.","Sie beendete die Aufgabe vor dem Zeitplan.","complete an assignment|work assignment"],
["asylum","Asyl","The family was granted asylum after fleeing the war.","Der Familie wurde nach der Flucht vor dem Krieg Asyl gewährt.","seek asylum|grant asylum"],
["atmosphere","Atmosphäre|Stimmung","The office has a relaxed atmosphere.","Das Büro hat eine entspannte Atmosphäre.","tense atmosphere|create an atmosphere"],
["attendance","Anwesenheit|Teilnehmerzahl","Attendance at the meeting was higher than expected.","Die Teilnehmerzahl bei dem Meeting war höher als erwartet.","poor attendance|record attendance"],
["attic","Dachboden","We store old boxes in the attic.","Wir lagern alte Kartons auf dem Dachboden.","clear out the attic|attic space"],
["attitude","Einstellung|Haltung","He has a positive attitude towards change.","Er hat eine positive Einstellung gegenüber Veränderungen.","positive attitude|change someone's attitude"],
["attorney","Anwalt|Anwältin","She hired an attorney to review the contract.","Sie beauftragte einen Anwalt, den Vertrag zu prüfen.","defense attorney|consult an attorney"],
["auditorium","Hörsaal|Auditorium","The lecture took place in the main auditorium.","Die Vorlesung fand im großen Hörsaal statt.","packed auditorium|school auditorium"],
["authority","Behörde|Autorität","The local authority approved the new building plan.","Die örtliche Behörde genehmigte den neuen Bauplan.","local authority|figure of authority"],
["autobiography","Autobiografie","He is writing his autobiography this year.","Er schreibt dieses Jahr seine Autobiografie.","publish an autobiography|bestselling autobiography"],
["backbone","Rückgrat|Fundament","Small businesses are the backbone of the local economy.","Kleine Unternehmen sind das Rückgrat der lokalen Wirtschaft.","the backbone of|form the backbone"],
["backdrop","Kulisse|Hintergrund","The negotiations took place against a backdrop of economic uncertainty.","Die Verhandlungen fanden vor dem Hintergrund wirtschaftlicher Unsicherheit statt.","against a backdrop|scenic backdrop"],
["backlog","Rückstand|Rückstau","There is a backlog of orders to process.","Es gibt einen Rückstand an Bestellungen, die bearbeitet werden müssen.","clear a backlog|growing backlog"],
["bandwidth","Bandbreite|Kapazität","We don't have the bandwidth to take on another project.","Wir haben nicht die Kapazität, ein weiteres Projekt zu übernehmen.","limited bandwidth|internet bandwidth"],
["bankruptcy","Insolvenz|Bankrott","The company filed for bankruptcy last month.","Das Unternehmen meldete letzten Monat Insolvenz an.","file for bankruptcy|declare bankruptcy"],
["barrier","Hindernis|Barriere","Language can be a barrier to communication.","Sprache kann ein Hindernis für die Kommunikation sein.","break down barriers|trade barrier"],
["baseline","Ausgangswert|Basislinie","We measured performance against the baseline.","Wir haben die Leistung mit dem Ausgangswert verglichen.","establish a baseline|baseline measurement"],
["bearing","Bezug|Auswirkung","Her comments have no bearing on the decision.","Ihre Kommentare haben keinen Bezug zu der Entscheidung.","have a bearing on|lose one's bearings"],
["belonging","Zugehörigkeit","The team activities create a sense of belonging.","Die Teamaktivitäten schaffen ein Gefühl der Zugehörigkeit.","a sense of belonging|feeling of belonging"],
["boundary","Grenze","It's important to set clear boundaries at work.","Es ist wichtig, am Arbeitsplatz klare Grenzen zu setzen.","set boundaries|cross a boundary"],
["breakthrough","Durchbruch","Scientists made a breakthrough in cancer research.","Wissenschaftler erzielten einen Durchbruch in der Krebsforschung.","major breakthrough|achieve a breakthrough"],
["breakup","Trennung|Auflösung","The breakup of the merger surprised the market.","Die Auflösung der Fusion überraschte den Markt.","painful breakup|breakup of a deal"],
["breeze","Brise|leichte Aufgabe","A cool breeze came in through the window.","Eine kühle Brise kam durchs Fenster herein.","gentle breeze|a breeze to do"],
["bulletin","Mitteilung|Rundschreiben","The company posted a bulletin about the new policy.","Das Unternehmen veröffentlichte ein Rundschreiben zur neuen Richtlinie.","news bulletin|post a bulletin"],
["bureaucracy","Bürokratie","Dealing with the bureaucracy took several weeks.","Der Umgang mit der Bürokratie dauerte mehrere Wochen.","cut through bureaucracy|excessive bureaucracy"],
["burnout","Erschöpfung|Burnout","Overwork led to burnout among the staff.","Überarbeitung führte bei den Mitarbeitern zu Burnout.","suffer burnout|risk of burnout"],
["campaign","Kampagne","The marketing team launched a new campaign.","Das Marketingteam startete eine neue Kampagne.","launch a campaign|advertising campaign"],
["candidate","Kandidat|Bewerber","Three candidates applied for the position.","Drei Kandidaten bewarben sich um die Stelle.","shortlist a candidate|ideal candidate"],
["capacity","Kapazität|Fähigkeit","The factory is running at full capacity.","Die Fabrik läuft mit voller Kapazität.","full capacity|capacity to learn"],
["caption","Bildunterschrift|Untertitel","The photo needs a short caption.","Das Foto braucht eine kurze Bildunterschrift.","write a caption|photo caption"],
["catalyst","Katalysator|Auslöser","The new CEO was a catalyst for change.","Der neue CEO war ein Katalysator für Veränderungen.","act as a catalyst|catalyst for growth"],
["catalogue","Katalog","You can order the parts from the online catalogue.","Du kannst die Teile aus dem Online-Katalog bestellen.","product catalogue|browse a catalogue"],
["ceasefire","Waffenstillstand","Both sides agreed to a ceasefire.","Beide Seiten stimmten einem Waffenstillstand zu.","declare a ceasefire|fragile ceasefire"],
["ceremony","Zeremonie|Feier","The award ceremony took place in the evening.","Die Preisverleihung fand am Abend statt.","opening ceremony|wedding ceremony"],
["checklist","Checkliste","She went through the checklist before the flight.","Sie ging vor dem Flug die Checkliste durch.","follow a checklist|tick off a checklist"],
["chore","lästige Aufgabe|Hausarbeit","Doing the laundry is his least favourite chore.","Wäsche waschen ist seine am wenigsten geliebte Hausarbeit.","household chore|daily chore"],
["clarity","Klarheit","The report lacked clarity on the next steps.","Der Bericht ließ Klarheit über die nächsten Schritte vermissen.","bring clarity|lack of clarity"],
["clause","Klausel","The contract includes a termination clause.","Der Vertrag enthält eine Kündigungsklausel.","termination clause|insert a clause"],
["clutter","Unordnung|Durcheinander","She cleared the clutter off her desk.","Sie räumte das Durcheinander von ihrem Schreibtisch.","clear the clutter|visual clutter"],
["coincidence","Zufall","Meeting her there was a pure coincidence.","Sie dort zu treffen war reiner Zufall.","pure coincidence|by coincidence"],
["collision","Kollision|Zusammenstoß","The two cars avoided a collision at the last second.","Die beiden Autos vermieden im letzten Moment einen Zusammenstoß.","avoid a collision|head-on collision"],
["commodity","Ware|Rohstoff","Oil is a commodity traded worldwide.","Öl ist ein weltweit gehandelter Rohstoff.","trade a commodity|commodity price"],
["commuter","Pendler","Commuters faced long delays this morning.","Pendler hatten heute Morgen mit langen Verspätungen zu kämpfen.","daily commuter|commuter train"],
["compassion","Mitgefühl","She treated every patient with compassion.","Sie behandelte jeden Patienten mit Mitgefühl.","show compassion|act with compassion"],
["compensation","Entschädigung|Vergütung","The airline offered compensation for the delay.","Die Fluggesellschaft bot eine Entschädigung für die Verspätung an.","seek compensation|fair compensation"],
["competence","Kompetenz|Fähigkeit","The team demonstrated strong technical competence.","Das Team zeigte starke technische Kompetenz.","core competence|professional competence"],
["component","Komponente|Bestandteil","Trust is a key component of a good team.","Vertrauen ist ein zentraler Bestandteil eines guten Teams.","key component|electronic component"],
["concession","Zugeständnis|Konzession","Both sides made concessions during the negotiation.","Beide Seiten machten während der Verhandlung Zugeständnisse.","make a concession|major concession"],
["confrontation","Konfrontation|Auseinandersetzung","He avoided a direct confrontation with his boss.","Er vermied eine direkte Konfrontation mit seinem Chef.","avoid confrontation|heated confrontation"],
["congestion","Stau|Überlastung","Traffic congestion delayed our arrival.","Verkehrsstau verzögerte unsere Ankunft.","traffic congestion|ease congestion"],
["consensus","Konsens|Einigkeit","The board reached a consensus on the new strategy.","Der Vorstand erzielte einen Konsens über die neue Strategie.","reach a consensus|broad consensus"],
["consequence","Konsequenz|Folge","Every decision has consequences.","Jede Entscheidung hat Konsequenzen.","face the consequences|serious consequence"],
["constraint","Einschränkung|Zwang","Budget constraints limited the project's scope.","Budgetbeschränkungen begrenzten den Umfang des Projekts.","budget constraint|under constraint"],
["consultation","Beratung|Konsultation","The doctor offers a free initial consultation.","Der Arzt bietet eine kostenlose Erstberatung an.","public consultation|schedule a consultation"],
["contingency","Eventualität|Notfallplan","We need a contingency plan in case the deal falls through.","Wir brauchen einen Notfallplan, falls der Deal scheitert.","contingency plan|allow for contingency"],
["contradiction","Widerspruch","There is a contradiction between the two reports.","Es gibt einen Widerspruch zwischen den beiden Berichten.","obvious contradiction|contradiction in terms"],
["contribution","Beitrag","Her contribution to the project was invaluable.","Ihr Beitrag zum Projekt war unschätzbar wertvoll.","make a contribution|significant contribution"],
["controversy","Kontroverse|Streit","The decision sparked controversy among employees.","Die Entscheidung löste unter den Mitarbeitern eine Kontroverse aus.","spark controversy|surrounded by controversy"],
["convenience","Bequemlichkeit|Annehmlichkeit","Online banking offers great convenience.","Online-Banking bietet großen Komfort.","for convenience|convenience store"],
["correspondence","Korrespondenz|Schriftverkehr","All correspondence should go through the legal team.","Der gesamte Schriftverkehr sollte über das Rechtsteam laufen.","business correspondence|regular correspondence"],
["counterpart","Gegenstück|Pendant","She met with her counterpart from the partner firm.","Sie traf sich mit ihrem Pendant von der Partnerfirma.","foreign counterpart|meet one's counterpart"],
["courtesy","Höflichkeit|Zuvorkommenheit","He replied out of courtesy, not obligation.","Er antwortete aus Höflichkeit, nicht aus Verpflichtung.","common courtesy|professional courtesy"],
["craftsmanship","Handwerkskunst","The furniture shows exceptional craftsmanship.","Die Möbel zeigen außergewöhnliche Handwerkskunst.","fine craftsmanship|traditional craftsmanship"],
["credential","Referenz|Qualifikation","Please list your credentials on the application.","Bitte geben Sie Ihre Qualifikationen in der Bewerbung an.","academic credentials|check someone's credentials"],
["crossroads","Scheideweg|Kreuzung","The company is at a crossroads after the merger.","Das Unternehmen steht nach der Fusion an einem Scheideweg.","at a crossroads|reach a crossroads"],
["curriculum","Lehrplan|Curriculum","The school updated its curriculum this year.","Die Schule aktualisierte dieses Jahr ihren Lehrplan.","school curriculum|revise the curriculum"],
["custody","Sorgerecht|Gewahrsam","The parents share custody of their children.","Die Eltern teilen sich das Sorgerecht für ihre Kinder.","share custody|take into custody"],
["database","Datenbank","All customer records are stored in the database.","Alle Kundendaten werden in der Datenbank gespeichert.","update a database|search a database"],
["deadline","Frist|Abgabetermin","We have to meet the deadline by Friday.","Wir müssen die Frist bis Freitag einhalten.","meet a deadline|tight deadline"],
["debris","Trümmer|Schutt","Workers cleared the debris after the storm.","Arbeiter räumten den Schutt nach dem Sturm weg.","clear debris|scattered debris"],
["decade","Jahrzehnt","Sales have grown steadily over the past decade.","Der Umsatz ist im letzten Jahrzehnt stetig gewachsen.","over a decade|the past decade"],
["deception","Täuschung|Betrug","The scheme relied on deception and false promises.","Das Schema beruhte auf Täuschung und leeren Versprechen.","practice deception|elaborate deception"],
["dedication","Hingabe|Engagement","Her dedication to the project impressed everyone.","Ihre Hingabe für das Projekt beeindruckte alle.","show dedication|dedication to work"],
["deficit","Defizit","The country is running a large trade deficit.","Das Land verzeichnet ein großes Handelsdefizit.","trade deficit|reduce the deficit"],
["delegation","Delegation|Abordnung","A delegation from headquarters visited the plant.","Eine Delegation aus der Zentrale besuchte das Werk.","trade delegation|lead a delegation"],
["demeanor","Auftreten|Wesen","She kept a calm demeanor throughout the interview.","Sie behielt während des gesamten Interviews ein ruhiges Auftreten.","calm demeanor|professional demeanor"],
["demographic","Bevölkerungsgruppe|Zielgruppe","The product targets a younger demographic.","Das Produkt richtet sich an eine jüngere Zielgruppe.","target demographic|shifting demographics"],
["denial","Leugnung|Dementi","The company issued a denial of the allegations.","Das Unternehmen veröffentlichte ein Dementi der Vorwürfe.","flat denial|state of denial"],
["deprivation","Entbehrung|Mangel","Sleep deprivation affects concentration and mood.","Schlafmangel beeinträchtigt Konzentration und Stimmung.","sleep deprivation|suffer deprivation"],
["designation","Bezeichnung|Einstufung","The building received a historic designation.","Das Gebäude erhielt den Status eines historischen Baudenkmals.","official designation|receive a designation"],
["despair","Verzweiflung","She felt a moment of despair after the rejection.","Sie fühlte nach der Absage einen Moment der Verzweiflung.","sink into despair|cry of despair"],
["destination","Reiseziel|Bestimmungsort","Paris remains a popular tourist destination.","Paris bleibt ein beliebtes Reiseziel.","popular destination|final destination"],
["deterrent","Abschreckung|Hemmnis","High prices act as a deterrent to new customers.","Hohe Preise wirken als Abschreckung für neue Kunden.","act as a deterrent|effective deterrent"],
["devotion","Hingabe|Ergebenheit","His devotion to his craft is admirable.","Seine Hingabe an sein Handwerk ist bewundernswert.","devotion to duty|show devotion"],
["dialect","Dialekt|Mundart","She speaks a regional dialect at home.","Sie spricht zu Hause einen regionalen Dialekt.","local dialect|speak a dialect"],
["dilemma","Dilemma|Zwickmühle","The manager faced a difficult dilemma.","Der Manager stand vor einem schwierigen Dilemma.","face a dilemma|moral dilemma"],
];

export const N2: RawEntry[] = [
["diligence","Sorgfalt|Fleiß","She approached the audit with great diligence.","Sie ging die Prüfung mit großer Sorgfalt an.","due diligence|work with diligence"],
["diploma","Diplom|Abschlusszeugnis","He received his diploma after four years of study.","Er erhielt sein Diplom nach vier Jahren Studium.","earn a diploma|award a diploma"],
["disclaimer","Haftungsausschluss|Disclaimer","The website includes a legal disclaimer.","Die Website enthält einen rechtlichen Haftungsausschluss.","legal disclaimer|add a disclaimer"],
["discomfort","Unbehagen|Beschwerden","The tight shoes caused some discomfort.","Die engen Schuhe verursachten etwas Unbehagen.","cause discomfort|slight discomfort"],
["discontent","Unzufriedenheit","There is growing discontent among the staff.","Unter den Mitarbeitern wächst die Unzufriedenheit.","growing discontent|voice discontent"],
["discrepancy","Diskrepanz|Unstimmigkeit","There was a discrepancy between the two invoices.","Es gab eine Diskrepanz zwischen den beiden Rechnungen.","spot a discrepancy|minor discrepancy"],
["discretion","Diskretion|Ermessen","Use your discretion when handling sensitive data.","Nutzen Sie Ihr Ermessen im Umgang mit sensiblen Daten.","at one's discretion|handle with discretion"],
["disparity","Unterschied|Ungleichheit","There is a wide disparity in pay between the two roles.","Es besteht ein großer Unterschied im Gehalt zwischen den beiden Rollen.","wage disparity|glaring disparity"],
["disposition","Veranlagung|Wesensart","She has a cheerful disposition.","Sie hat eine fröhliche Wesensart.","sunny disposition|natural disposition"],
["disruption","Störung|Unterbrechung","The strike caused major disruption to services.","Der Streik verursachte erhebliche Störungen der Dienstleistungen.","cause disruption|minimal disruption"],
["domain","Bereich|Domäne","Marketing falls outside my domain of expertise.","Marketing fällt außerhalb meines Fachbereichs.","public domain|domain of expertise"],
["donor","Spender","The charity relies on regular donors.","Die Wohltätigkeitsorganisation ist auf regelmäßige Spender angewiesen.","generous donor|blood donor"],
["dormitory","Wohnheim|Schlafsaal","First-year students live in the dormitory.","Erstsemester wohnen im Wohnheim.","student dormitory|dormitory room"],
["downturn","Abschwung|Rückgang","The economy experienced a sharp downturn.","Die Wirtschaft erlebte einen starken Abschwung.","economic downturn|sharp downturn"],
["drawback","Nachteil","The plan's main drawback is the cost.","Der Hauptnachteil des Plans sind die Kosten.","main drawback|serious drawback"],
["drought","Dürre|Trockenheit","The region suffered a severe drought last summer.","Die Region litt letzten Sommer unter einer schweren Dürre.","severe drought|drought conditions"],
["duration","Dauer","The training lasts for the duration of one week.","Die Schulung dauert eine Woche.","for the duration|entire duration"],
["dwelling","Wohnstätte|Behausung","The area is zoned for residential dwellings only.","Das Gebiet ist ausschließlich für Wohngebäude ausgewiesen.","residential dwelling|modest dwelling"],
["eclipse","Finsternis|Eklipse","Thousands gathered to watch the solar eclipse.","Tausende versammelten sich, um die Sonnenfinsternis zu beobachten.","solar eclipse|total eclipse"],
["ecosystem","Ökosystem","The startup ecosystem in Berlin is thriving.","Das Start-up-Ökosystem in Berlin floriert.","digital ecosystem|fragile ecosystem"],
["eloquence","Eloquenz|Redegewandtheit","He spoke with great eloquence at the ceremony.","Er sprach bei der Zeremonie mit großer Eloquenz.","speak with eloquence|natural eloquence"],
["embargo","Embargo","The government imposed an embargo on the imports.","Die Regierung verhängte ein Embargo für die Importe.","impose an embargo|lift an embargo"],
["emergence","Aufkommen|Entstehung","The emergence of new technology changed the market.","Das Aufkommen neuer Technologie veränderte den Markt.","the emergence of|rapid emergence"],
["eminence","Bedeutung|Ansehen","He rose to eminence in his field.","Er stieg in seinem Fachgebiet zu Ansehen auf.","rise to eminence|position of eminence"],
["empathy","Empathie|Einfühlungsvermögen","Good managers show empathy towards their team.","Gute Führungskräfte zeigen Empathie gegenüber ihrem Team.","show empathy|lack of empathy"],
["enclosure","Gehege|Einfriedung","The zoo built a new enclosure for the lions.","Der Zoo baute ein neues Gehege für die Löwen.","animal enclosure|secure enclosure"],
["insight","Einblick|Erkenntnis","The survey gave us valuable insight into customer needs.","Die Umfrage gab uns wertvolle Einblicke in die Kundenbedürfnisse.","valuable insight|gain insight"],
["endeavor","Bestreben|Vorhaben","The research project was a joint endeavor.","Das Forschungsprojekt war ein gemeinsames Vorhaben.","joint endeavor|human endeavor"],
["endorsement","Empfehlung|Unterstützung","The product received a celebrity endorsement.","Das Produkt erhielt die Empfehlung eines Prominenten.","celebrity endorsement|full endorsement"],
["enrollment","Einschreibung|Anmeldung","University enrollment has increased this year.","Die Einschreibungen an der Universität sind dieses Jahr gestiegen.","student enrollment|open enrollment"],
["entity","Einheit|Rechtsträger","The subsidiary operates as a separate legal entity.","Die Tochtergesellschaft agiert als eigenständiger Rechtsträger.","legal entity|separate entity"],
["epidemic","Epidemie","Health officials declared an epidemic.","Gesundheitsbehörden erklärten eine Epidemie.","declare an epidemic|spread of an epidemic"],
["episode","Episode|Folge","The show's latest episode aired last night.","Die neueste Folge der Show wurde gestern Abend ausgestrahlt.","latest episode|watch an episode"],
["equilibrium","Gleichgewicht","The market eventually returns to equilibrium.","Der Markt kehrt schließlich ins Gleichgewicht zurück.","reach equilibrium|delicate equilibrium"],
["errand","Besorgung|Erledigung","She ran a few errands before work.","Sie erledigte vor der Arbeit ein paar Besorgungen.","run an errand|quick errand"],
["estate","Nachlass|Anwesen","He inherited a large estate from his grandfather.","Er erbte von seinem Großvater ein großes Anwesen.","real estate|manage an estate"],
["etiquette","Etikette|Umgangsformen","Business etiquette varies across cultures.","Geschäftsetikette variiert je nach Kultur.","business etiquette|breach of etiquette"],
["eviction","Zwangsräumung|Kündigung","The tenants faced eviction after missing rent payments.","Den Mietern drohte eine Zwangsräumung, nachdem sie Mietzahlungen versäumt hatten.","face eviction|eviction notice"],
["exception","Ausnahme","We can make an exception in this case.","Wir können in diesem Fall eine Ausnahme machen.","make an exception|rare exception"],
["excerpt","Auszug|Ausschnitt","The teacher read an excerpt from the novel.","Die Lehrerin las einen Auszug aus dem Roman vor.","short excerpt|excerpt from a book"],
["exclusion","Ausschluss","The clause allows for the exclusion of certain risks.","Die Klausel erlaubt den Ausschluss bestimmter Risiken.","social exclusion|exclusion clause"],
["excursion","Ausflug|Exkursion","The class went on an excursion to the museum.","Die Klasse machte einen Ausflug ins Museum.","school excursion|day excursion"],
["exemption","Befreiung|Ausnahme","Charities often qualify for a tax exemption.","Wohltätigkeitsorganisationen qualifizieren sich oft für eine Steuerbefreiung.","tax exemption|claim an exemption"],
["exhibition","Ausstellung","The gallery is hosting a new art exhibition.","Die Galerie veranstaltet eine neue Kunstausstellung.","art exhibition|hold an exhibition"],
["expedition","Expedition","The team set out on an expedition to the Arctic.","Das Team brach zu einer Expedition in die Arktis auf.","scientific expedition|mount an expedition"],
["expenditure","Ausgabe|Aufwand","Household expenditure rose sharply this quarter.","Die Haushaltsausgaben stiegen in diesem Quartal stark an.","public expenditure|reduce expenditure"],
["expertise","Fachwissen|Expertise","We rely on her expertise in tax law.","Wir verlassen uns auf ihre Expertise im Steuerrecht.","technical expertise|area of expertise"],
["extension","Verlängerung|Anbau","She requested an extension on the deadline.","Sie beantragte eine Verlängerung der Frist.","request an extension|building extension"],
["facade","Fassade","Behind the calm facade, he was worried.","Hinter der ruhigen Fassade war er besorgt.","put up a facade|building facade"],
["faction","Fraktion|Splittergruppe","The party split into two rival factions.","Die Partei spaltete sich in zwei rivalisierende Fraktionen.","rival faction|internal faction"],
["fallout","Nachwirkung|Folgen","The company is still dealing with the fallout from the scandal.","Das Unternehmen kämpft noch mit den Folgen des Skandals.","political fallout|deal with the fallout"],
["fatigue","Erschöpfung|Müdigkeit","Chronic fatigue affected her concentration.","Chronische Erschöpfung beeinträchtigte ihre Konzentration.","suffer from fatigue|mental fatigue"],
["feasibility","Machbarkeit","The team conducted a feasibility study first.","Das Team führte zunächst eine Machbarkeitsstudie durch.","feasibility study|assess feasibility"],
["fiasco","Fiasko|Debakel","The product launch turned into a complete fiasco.","Die Produkteinführung wurde zu einem völligen Fiasko.","complete fiasco|turn into a fiasco"],
["fixture","Fixpunkt|feste Einrichtung","The Friday meeting has become a permanent fixture.","Das Freitagsmeeting ist zu einer festen Einrichtung geworden.","permanent fixture|light fixture"],
["flair","Gespür|Talent","She has a natural flair for design.","Sie hat ein natürliches Gespür für Design.","natural flair|flair for languages"],
["flaw","Fehler|Mangel","The plan has one obvious flaw.","Der Plan hat einen offensichtlichen Fehler.","fatal flaw|obvious flaw"],
["fluency","Sprachgewandtheit|Fließend-Sein","Fluency in English is required for this role.","Für diese Rolle wird fließendes Englisch vorausgesetzt.","achieve fluency|native-like fluency"],
["forefront","Spitze|Vorderfront","The company is at the forefront of innovation.","Das Unternehmen steht an der Spitze der Innovation.","at the forefront|forefront of research"],
["forerunner","Vorläufer|Wegbereiter","The device was a forerunner of the modern smartphone.","Das Gerät war ein Vorläufer des modernen Smartphones.","forerunner of|early forerunner"],
["foresight","Weitsicht|Voraussicht","It took great foresight to invest early.","Es erforderte große Weitsicht, frühzeitig zu investieren.","lack foresight|show foresight"],
["forgery","Fälschung","The painting turned out to be a forgery.","Das Gemälde stellte sich als Fälschung heraus.","detect a forgery|art forgery"],
["formality","Formalität","Signing the papers is just a formality.","Die Papiere zu unterschreiben ist nur eine Formalität.","mere formality|legal formality"],
["foundation","Fundament|Stiftung","Trust forms the foundation of any partnership.","Vertrauen bildet das Fundament jeder Partnerschaft.","lay the foundation|charitable foundation"],
["fragment","Fragment|Bruchstück","Only a fragment of the original document survives.","Nur ein Fragment des Originaldokuments ist erhalten.","small fragment|fragment of evidence"],
["framework","Rahmen|Rahmenwerk","The team developed a framework for decision-making.","Das Team entwickelte einen Rahmen für die Entscheidungsfindung.","legal framework|develop a framework"],
["fraternity","Bruderschaft|Verbindung","He joined a fraternity during his first year at college.","Er trat im ersten Studienjahr einer Studentenverbindung bei.","college fraternity|sense of fraternity"],
["frontier","Grenze|Grenzgebiet","The discovery pushed the frontier of medical science.","Die Entdeckung erweiterte die Grenzen der Medizinwissenschaft.","push the frontier|new frontier"],
["fulfillment","Erfüllung","She found great fulfillment in teaching.","Sie fand in der Lehre große Erfüllung.","sense of fulfillment|personal fulfillment"],
["furnishing","Einrichtung|Möblierung","The apartment comes with basic furnishings.","Die Wohnung wird mit einer Grundausstattung geliefert.","home furnishing|basic furnishing"],
["gadget","Gerät|Gimmick","He loves trying out the latest tech gadgets.","Er probiert gerne die neuesten technischen Geräte aus.","handy gadget|latest gadget"],
["gala","Gala|Festveranstaltung","The company hosted a charity gala last weekend.","Das Unternehmen veranstaltete letztes Wochenende eine Wohltätigkeitsgala.","charity gala|annual gala"],
["gap","Lücke|Abstand","There is a growing gap between supply and demand.","Es besteht eine wachsende Lücke zwischen Angebot und Nachfrage.","close the gap|generation gap"],
["garment","Kleidungsstück","Each garment is inspected before shipping.","Jedes Kleidungsstück wird vor dem Versand geprüft.","designer garment|inspect a garment"],
["gathering","Versammlung|Treffen","The annual gathering brings together alumni from around the world.","Das jährliche Treffen bringt Absolventen aus aller Welt zusammen.","social gathering|family gathering"],
["genre","Genre|Gattung","Science fiction is her favourite literary genre.","Science-Fiction ist ihr liebstes literarisches Genre.","literary genre|film genre"],
["gesture","Geste","Sending flowers was a kind gesture.","Blumen zu schicken war eine nette Geste.","kind gesture|symbolic gesture"],
["glimpse","flüchtiger Blick|Einblick","The report offers a glimpse into future trends.","Der Bericht bietet einen Einblick in zukünftige Trends.","catch a glimpse|brief glimpse"],
["gratitude","Dankbarkeit","She expressed her gratitude to the whole team.","Sie brachte dem gesamten Team ihre Dankbarkeit zum Ausdruck.","express gratitude|deep gratitude"],
["grievance","Beschwerde|Missstand","Employees can file a formal grievance with HR.","Mitarbeiter können bei der Personalabteilung eine formelle Beschwerde einreichen.","file a grievance|air a grievance"],
["guardian","Vormund|Wächter","The court appointed a legal guardian for the child.","Das Gericht bestellte einen gesetzlichen Vormund für das Kind.","legal guardian|appoint a guardian"],
["guideline","Richtlinie|Leitfaden","Please follow the new safety guidelines.","Bitte befolgen Sie die neuen Sicherheitsrichtlinien.","safety guideline|follow a guideline"],
["habitat","Lebensraum|Habitat","Deforestation threatens the animals' natural habitat.","Abholzung bedroht den natürlichen Lebensraum der Tiere.","natural habitat|destroy a habitat"],
["hallmark","Kennzeichen|Markenzeichen","Attention to detail is the hallmark of her work.","Liebe zum Detail ist das Markenzeichen ihrer Arbeit.","hallmark of quality|distinctive hallmark"],
["harassment","Belästigung|Schikane","The company has a strict policy against harassment.","Das Unternehmen hat eine strikte Richtlinie gegen Belästigung.","sexual harassment|report harassment"],
["hardship","Not|Härte","The family endured great financial hardship.","Die Familie erlitt große finanzielle Not.","financial hardship|endure hardship"],
["hazard","Gefahr|Risiko","Loose cables are a tripping hazard in the office.","Lose Kabel stellen im Büro eine Stolpergefahr dar.","health hazard|potential hazard"],
["heirloom","Erbstück","The ring is a family heirloom passed down for generations.","Der Ring ist ein Familienerbstück, das seit Generationen weitergegeben wird.","family heirloom|treasured heirloom"],
["heritage","Erbe|Kulturerbe","The old town is protected as cultural heritage.","Die Altstadt steht als Kulturerbe unter Schutz.","cultural heritage|heritage site"],
["hierarchy","Hierarchie","Decisions must go through the corporate hierarchy.","Entscheidungen müssen die Unternehmenshierarchie durchlaufen.","corporate hierarchy|climb the hierarchy"],
["hindsight","Rückblick|Rückschau","In hindsight, we should have tested the product sooner.","Im Rückblick hätten wir das Produkt früher testen sollen.","in hindsight|20/20 hindsight"],
["horizon","Horizont","New markets broadened the company's horizon.","Neue Märkte erweiterten den Horizont des Unternehmens.","broaden one's horizon|on the horizon"],
["hospitality","Gastfreundschaft|Gastgewerbe","The hosts were known for their warm hospitality.","Die Gastgeber waren für ihre herzliche Gastfreundschaft bekannt.","warm hospitality|hospitality industry"],
["hostility","Feindseligkeit","There was open hostility between the two departments.","Zwischen den beiden Abteilungen herrschte offene Feindseligkeit.","open hostility|show hostility"],
["hunch","Ahnung|Vermutung","She had a hunch that something was wrong.","Sie hatte die Ahnung, dass etwas nicht stimmte.","have a hunch|follow a hunch"],
["hygiene","Hygiene","Good hygiene practices reduce the spread of illness.","Gute Hygienepraktiken verringern die Verbreitung von Krankheiten.","personal hygiene|hygiene standards"],
["identity","Identität","The brand has built a strong identity over the years.","Die Marke hat über die Jahre eine starke Identität aufgebaut.","brand identity|prove one's identity"],
["illusion","Illusion|Täuschung","The discount creates an illusion of savings.","Der Rabatt erzeugt eine Illusion von Ersparnis.","create an illusion|under the illusion"],
["impulse","Impuls|spontaner Drang","She bought the jacket on impulse.","Sie kaufte die Jacke aus einem spontanen Impuls heraus.","buy on impulse|sudden impulse"],
["incentive","Anreiz","The bonus is a strong incentive to perform well.","Der Bonus ist ein starker Anreiz, gute Leistungen zu erbringen.","financial incentive|provide an incentive"],
];
